- src/control-plane/backend/click-stream-api.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- test/control-plane/click-stream-api.test.ts
----
1. catch InternalFailure Exception
2. set quicksight default control plane region in China region
Closes: #10 
> fix: quicksight check in china region

- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow.test.ts
> fix: allow change the interval of data processing when editing pipeline

- src/control-plane/backend/lambda/api/common/constants.ts
- src/control-plane/backend/lambda/api/common/request-valid.ts
- src/control-plane/backend/lambda/api/router/plugin.ts
- src/control-plane/backend/lambda/api/test/api/plugin.test.ts
----
For security reasons, restrict the suffix of uploaded files (`jar, mmdb`)
Allow file suffix could edit by lambda environment variable: **ALLOW_UPLOADED_FILE_TYPES**
> feat(api): add file type validation for uploading plug-ins

- src/control-plane/backend/click-stream-api.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- test/control-plane/click-stream-api.test.ts
----
https://github.com/awslabs/clickstream-analytics-on-aws/pull/12#issuecomment-1632076735
> fix: quicksight check in china regions

- .dockerignore
- .github/workflows/dist-scan.yml
- .projenrc.js
- Dockerfile.backend.build
- src/control-plane/backend/click-stream-api.ts
- src/control-plane/backend/lambda/api/run.sh
- src/control-plane/backend/lambda/api/tsconfig.dev.json
- src/control-plane/backend/lambda/api/tsconfig.json
- src/control-plane/backend/layer/lambda-web-adapter/Dockerfile
- src/control-plane/backend/layer/lambda-web-adapter/layer.ts
- test/control-plane/click-stream-api.test.ts
- test/control-plane/cloudfront-control-plane-stack.test.ts
----
1. Create lambda adapter layer for backend lambda.
2. Docker build backend to Zip.
> chore: deploy backend lambda as zip

- frontend/src/pages/pipelines/create/CreatePipeline.tsx
- frontend/src/pages/pipelines/create/steps/Reporting.tsx
- frontend/src/ts/init.ts
- frontend/src/types/pipeline.d.ts
- src/common/constant.ts
- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
- src/data-reporting-quicksight-stack.ts
- src/reporting/lambda/custom-resource/quicksight/index.ts
- src/reporting/parameter.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
----
1. put quicksight **user arn** to backend.
1.  Api (`ListUsers, RegisterUser`) auto check quicksight main region  
2. Add parameter **QuickSightPrincipal** to reporting stack
1. Use stack parameter instead of fixed pattern as principal value
> fix: use stack parameter instead of fixed pattern as principal value when create QuickSight report

- src/analytics/lambdas/custom-resource/create-schemas.ts
- src/reporting/lambda/custom-resource/quicksight/index.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
----
change all md5 hash fun to sha256 to improve security level
> chore: change md5 hash to sha256

- src/control-plane/auth/authorizer.ts
- src/control-plane/backend/lambda/api/middle-ware/auth-oidc.ts
- src/control-plane/backend/lambda/api/test/api/app.test.ts
- src/control-plane/backend/lambda/api/test/api/auth.test.ts
- test/control-plane/lambda/auth.test.ts
> chore: add unit test to auth lambda

- src/control-plane/backend/click-stream-api.ts
- test/control-plane/alb-control-plane-stack.test.ts
- test/control-plane/click-stream-api.test.ts
- test/control-plane/cloudfront-control-plane-stack.test.ts
> fix: replace api function resource id

- src/control-plane/cloudfront-s3-portal.ts
- test/control-plane/cloudfront-s3-portal.test.ts
----
- update CloudFront Price class to 100 level 
- test deploy in global region
- test deploy in China region
> chore: update CloudFront price class level

- src/ingestion-server/server/images/vector/Dockerfile
- src/ingestion-server/server/images/vector/config/vector-kinesis-ack.toml
----
upgrade vector to 0.31.0 version and enable retry for KDS
relate to #9 
> fix: enable retry for KDS

- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow.test.ts
> fix: edit pipeline not allow data processing cron or rate expression

- src/control-plane/backend/layer/lambda-web-adapter/layer.ts
- test/control-plane/click-stream-api.test.ts
> fix: delete CompatibleArchitectures for lambda layer

- src/control-plane/backend/lambda/sfn-action/index.ts
- test/control-plane/lambda/sfn-action.test.ts
> fix: retry the failed stacks

- src/reporting/private/template-def.json
----
update QuickSight dashboard - device sheet
make timeStart and timeEnd filter take effect
fix #61 
update device report and regenerate analysis template definition
> fix: apply time filter for the visuals of device report

- src/analytics/lambdas/custom-resource/create-schemas.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
----
update redshift user password format to meet QuickSight connection's requirement
> fix: update password format to meet QuickSight connection's requirement

- src/reporting/private/template-def.json
----
update QuickSight dashboard - retention sheet
make timeStart and timeEnd filter take effect
update retention report and regenerate analysis template definition
> fix: apply time filter for the visuals of rentention report 

- src/ingestion-server/server/images/nginx/Dockerfile
----
Upgrade nginx from 1.22 to 1.25
closes #9 
> chore(deps): upgrade nginx to stable 1.24

- .github/workflows/build-sub-projects.yml
- .github/workflows/build.yml
- .github/workflows/upgrade.yml
- .projenrc.js
----
there is some additional repo setting,
-  read/write content
- read/write pull request
- read/write workflow
> chore: configure weekly dependencies update

- src/control-plane/backend/layer/lambda-web-adapter/Dockerfile
- src/control-plane/backend/layer/lambda-web-adapter/bootstrap
> chore: copy extensions asset from lambda-adapter image

- frontend/src/ts/const.ts
- src/ingestion-server/kafka-s3-connector/custom-resource/kafka-s3-sink-connector/index.ts
- test/ingestion-server/kafka-s3-connector/custom-resource/kafka-s3-sink-connector.test.ts
----
Enable self-kafka and ignore invalid format message in kafka connector
1. Enable control plane to support self-hosted kafka cluster
2. Add configuration to make kafka connector to ignore invalid format message.
> feat: enable self-kafka and ignore invalid format message in kafka connector

- .github/workflows/build-sub-projects.yml
- .github/workflows/build.yml
- .github/workflows/dist-scan.yml
- .projenrc.js
----
Login public ecr when the secret `ROLE_ARN` if it exists
Below are the procedures to generate the role to meet the requirements with least privilege,
1. use [the template](https://github.com/aws-actions/configure-aws-credentials#sample-iam-oidc-cloudformation-template) to create the identity provider of Github and IAM role
2. grant the role with [permission to login public ecr](https://github.com/aws-actions/configure-aws-credentials#sample-iam-oidc-cloudformation-template)
3. create an action secret `ROLE_ARN` in repo with the value of role arn created by step 1
**Note**: it only helps the committers to submit PR in this repo. Due to we store the role arn in secret …
> chore: mitigate toomany requests when pulling from public ecr in github actions

- src/ingestion-server/server/private/alb.ts
- test/ingestion-server/server/ingestion-server.test.ts
----
enable ALB drop_invalid_header_fields attribute
1. enable ALB drop_invalid_header_fields attribute
2. Add Unit test case
> chore: enable ALB drop_invalid_header_fields attribute

- frontend/public/locales/en/pipeline.json
- frontend/public/locales/zh/pipeline.json
- frontend/src/pages/pipelines/create/CreatePipeline.tsx
- frontend/src/pages/pipelines/create/steps/DataProcessing.tsx
- src/analytics/parameter.ts
- src/common/constant.ts
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
> fix: check Redshift DB user in both frontend and backend

- src/common/constant.ts
- src/common/utils.ts
- src/control-plane/backend/click-stream-api.ts
- src/control-plane/backend/lambda/api/common/constants.ts
- src/control-plane/backend/lambda/api/common/dynamodb-client.ts
- src/control-plane/backend/lambda/api/common/request-valid.ts
- src/control-plane/backend/lambda/api/common/types.ts
- src/control-plane/backend/lambda/api/index.ts
- src/control-plane/backend/lambda/api/model/metadata.ts
- src/control-plane/backend/lambda/api/router/metadata.ts
- src/control-plane/backend/lambda/api/service/metadata.ts
- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
- src/control-plane/backend/lambda/api/store/metadata-store.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/metadata.test.ts
- test/control-plane/click-stream-api.test.ts
----
1. Add DDB table for metadata of project/app events.
2. Add new api **/api/metadata** for `event`, `event attribute`, `user attribute`
> feat: backend metadata manage api

- src/common/constant.ts
- src/common/lambda.ts
- src/data-pipeline-stack.ts
- src/data-pipeline/data-pipeline.ts
- src/data-pipeline/lambda/emr-serverless-app/index.ts
- src/data-pipeline/parameter.ts
- src/data-pipeline/utils/custom-resource.ts
- test/data-pipeline/data-pipeline-stack.test.ts
- test/data-pipeline/emr-serverless-app.test.ts
----
1. create new EMR-serverless application when update/upgrade via custom resource
2. try to delete old applications if they can be deleted
3. add two parameters:
- EmrVersion, default value: `emr-6.11.0`
- EmrApplicationIdleTimeoutMinutes, default value: `5`
> fix: emr-serverless application upgrade issue when the state is started 

- src/data-pipeline/lambda/emr-serverless-app/index.ts
----
The installation gets error:
"Cannot read properties of undefined(reading X86_64)" in `node.js18`.  
No problem when set lambda runtime to `node.js16` in CDK. 
> fix: error in node.js18 when using Architecture.X86_64

- .github/workflows/build.yml
- .github/workflows/upgrade.yml
- .projenrc.js
- README.md
- package.json
- src/control-plane/backend/lambda/api/package.json
> chore: downgrade minimum node to 18.16.1 for codebuild support

- .github/PULL_REQUEST_TEMPLATE.md
- deployment/run-unit-tests.sh
> fix: the run-unit-tests script fails with tests in codebuild

- src/alb-control-plane-stack.ts
- src/control-plane/backend/click-stream-api.ts
- test/control-plane/click-stream-api.test.ts
> fix: grant api function access to read and write metadata table

- src/ingestion-server/server/private/ecs-cluster.ts
- test/ingestion-server/server/ingestion-server.test.ts
----
Make the warm pool size can be set from value of "WarmPoolSize" of cloudformation parameter
1. Set the "MaxGroupPreparedCapacity" value as "WarmPoolSize" value. According to [document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-autoscaling-warmpool.html#cfn-autoscaling-warmpool-maxgrouppreparedcapacity)    
`The size of the warm pool is dynamic. Only when MaxGroupPreparedCapacity and MinSize are set to the same value does the warm pool have an absolute size.`
2. Tested cases as below:
| Asg-MinSize   | Asg-MaxSize    | WarmPoolSize           |  real-warm-pool-size |
|---------|---------|---------|---------|
2                      |    4 …
> fix: set the warm pool size

- .github/workflows/build.yml
- .github/workflows/upgrade.yml
- .projenrc.js
- README.md
- buildspec.yml
- package.json
- src/control-plane/backend/lambda/api/package.json
> chore: bump minimum node to 18.17.0

- sonar-project.properties
> chore: exclude the false positive rule when instantiating CDK objects

- deployment/build-open-source-dist.sh
> fix: keep build assets when building package

- .viperlightignore
- frontend/package.json
- frontend/public/locales/en/analytics.json
- frontend/public/locales/en/common.json
- frontend/public/locales/zh/analytics.json
- frontend/public/locales/zh/common.json
- frontend/src/apis/analytics.ts
- frontend/src/pages/analytics/comps/DashboardHeader.tsx
- frontend/src/pages/analytics/dashboard/AnalyticsDashboard.tsx
- frontend/src/pages/analytics/dashboard/create/CreateDashboard.tsx
- frontend/src/pages/analytics/dashboard/detail/AnalyticsDashboardDetail.tsx
- frontend/src/types/analytics.d.ts
- frontend/yarn.lock
- src/control-plane/backend/lambda/api/model/project.ts
- src/control-plane/backend/lambda/api/router/project.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/store/click-stream-store.ts
- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
- src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/env-bucket-policy.test.ts
----
1. [**backend**] Add api for dashboards.
2. [**frontend**] Create dashboards && delete dashboards
3. [**frontend**] Embedding dashboard url parameters get from dashboard detail
> feat: Dashboards management

- src/ingestion-server/custom-resource/update-alb-rules.ts
- src/ingestion-server/custom-resource/update-alb-rules/index.ts
- test/ingestion-server/custom-resource/update-alb-rules.test.ts
----
close #128 
Fix the issue of unable to updating endpoint path in ALB rule.
1. Update update alb rules lambda to cover endpoint path updating.
2. Add unit test cases
3. Test below cases:
- Just update endpoint path from /collect to /g/collect 
- Update appIds from "notepad1,notepad2" to "notepad3,notepad2,notepad4", endpoint path from /g/collect to /collectnew
- Update appIds from "notepad3,notepad2,notepad4" to "notepad3", without changing endpoint path
> fix: can not update endpoint path in some cases

- src/ingestion-server/custom-resource/update-alb-rules.ts
- src/ingestion-server/custom-resource/update-alb-rules/index.ts
- test/ingestion-server/custom-resource/update-alb-rules.test.ts
----
Fix the issue of unable to updating endpoint path in ALB rule.
1. Update update alb rules lambda to cover endpoint path updating.
2. Add unit test cases
3. Test below cases:
- Update appIds from "notepad1,notepad2" to "notepad3,notepad2,notepad4", endpoint path from /collect to /g/collect
> fix: can not update endpoint path of ingestion sever

- src/common/constant.ts
- src/control-plane/backend/lambda/api/test/api/utils.test.ts
- src/ingestion-server/server/parameter.ts
- test/ingestion-server/server/ingestion-server-stack.test.ts
…on server stack
----
Add stack cors pattern to check ServerCorsOrigin parameter of ingestion server stack
1. Add stack cors pattern to check ServerCorsOrigin parameter of ingestion server stack
2. Add Unit test cases
3. Verify below input from Ingestion stack:
- .*
- ''
- http://abc1\.test\.com|http://abc2\.test\.com|https://abc3\.test\.com|http://localhost|http://127.0.0.1|http://.*\.example\.com
- http://localhost:8002
> fix: Add stack cors pattern to check ServerCorsOrigin parameter of ingestion server stack

- src/common/constant.ts
- src/control-plane/backend/lambda/api/test/api/utils.test.ts
- test/ingestion-server/server/ingestion-server-stack.test.ts
----
fix domain name pattern
fix domain name pattern to match TLD standard
Deploy ingestion stack as below DomainName parameter:
DomainName: example.services
DomainName: cs-3.us1.xxx.xxx.solutions.aws.a2z.org.cn
> fix: fix domain name pattern

- frontend/public/locales/en/analytics.json
- frontend/public/locales/zh/analytics.json
- frontend/src/index.scss
- frontend/src/pages/analytics/analytics-utils.ts
- frontend/src/pages/analytics/comps/ExploreEmbedFrame.tsx
- frontend/src/pages/analytics/event/AnalyticsEvent.tsx
- frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
- frontend/src/types/analytics.d.ts
- src/control-plane/backend/lambda/api/common/explore-types.ts
- src/control-plane/backend/lambda/api/common/sdk-client.ts
- src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/test/api/env.test.ts
- src/control-plane/backend/lambda/api/test/api/reporting-utils.test.ts
- src/control-plane/backend/lambda/api/test/api/reporting.test.ts
----
1. Reuse front-end components `ExploreEmbedFrame`
2. SDK Client Cache
3. Optimize explore **resource create stage**: the explore api returns embed URL at the same time, not fetch from frontend. 
Old stage:
1. Request explore api to create Quicksight resource and Redshift view, return `dashboardId, sheetId, visualId`.
2. Request embed api to get embed URL
New stage:
1. Request explore api create resource **and return embed URL**.
**Reduce time about 2～4 seconds at resource create stage**
> chore: optimize exploration query performance

- src/control-plane/backend/stack-action-state-machine-construct.ts
- test/control-plane/click-stream-api.test.ts
> fix: fail deploy ingestion stack with insufficient permission

- .viperlightignore
- frontend/public/locales/en/common.json
- frontend/public/locales/en/user.json
- frontend/public/locales/zh/common.json
- frontend/public/locales/zh/user.json
- frontend/src/apis/user.ts
- frontend/src/context/UserContext.ts
- frontend/src/pages/user/CreateUser.tsx
- frontend/src/pages/user/SettingUser.tsx
- frontend/src/pages/user/UserList.tsx
- frontend/src/pages/user/UserTable.tsx
- frontend/src/pages/user/UserTableHeader.tsx
- frontend/src/types/user.ts
- src/control-plane/backend/click-stream-api.ts
- src/control-plane/backend/insert-admin-user.ts
- src/control-plane/backend/lambda/api/common/constants.ts
- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/middle-ware/auth-role.ts
- src/control-plane/backend/lambda/api/model/user.ts
- src/control-plane/backend/lambda/api/router/user.ts
- src/control-plane/backend/lambda/api/service/user.ts
- src/control-plane/backend/lambda/api/store/click-stream-store.ts
- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
- src/control-plane/backend/lambda/api/test/api/auth.test.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/user.test.ts
- test/control-plane/click-stream-api.test.ts
- test/jestEnv.js
----
1. Delete User DDB table, move user data to metadata table.
2. Add create/delete user button on frontend.
3. Role in DDB overwrite role in token.
4. Add user settings at frontend.
> feat: refactor user management with new spec

- src/control-plane/backend/lambda/api/router/user.ts
- src/control-plane/backend/lambda/api/service/user.ts
- src/control-plane/backend/lambda/api/store/click-stream-store.ts
- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
- src/control-plane/backend/lambda/api/test/api/auth.test.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/user.test.ts
----
Move user settings from dictionary table to metadata table.
> fix: user setting is overwritten in dictionary table when update control plane

- src/analytics/analytics-on-redshift.ts
- src/analytics/lambdas/scan-metadata-workflow/check-scan-metadata-status.ts
- src/analytics/lambdas/scan-metadata-workflow/scan-metadata.ts
- src/analytics/lambdas/scan-metadata-workflow/store-metadata-into-ddb.ts
- src/analytics/parameter.ts
- src/analytics/private/constant.ts
- src/analytics/private/metircs-redshift-cluster.ts
- src/analytics/private/metircs-redshift-serverless.ts
- src/analytics/private/model.ts
- src/analytics/private/scan-metadata-workflow.ts
- src/analytics/private/sql-def.ts
- src/analytics/private/sqls/redshift/sp-scan-metadata.sql
- src/common/constant.ts
- src/data-analytics-redshift-stack.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
- test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/check-scan-metadata-status.test.ts
- test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/scan-metadata.test.ts
- test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/store-metadata-into-ddb.test.ts
- test/jestEnv.js
----
Scan metadata feature
Including below implementation:
1. Create scan metadata step function workflow to orchestrate the entire process
2. Stored procedure to aggregate data and store into a temp table.
3. Check stored procedure status
4. Store data into DynamoDB
5. Create Event Bridge Rule to trigger step function workflow daily.
ClickstreamAnalyticsMetadataDdbArn
- [] introduce new service permission in stack
> feat: add workflow for scaning event metadata in redshift then persist to DDB

- src/control-plane/backend/stack-action-state-machine-construct.ts
- test/control-plane/click-stream-api.test.ts
> fix: insufficient permission for ingestion server when missing required service roles for ecs and auto scaling

- .gitallowed
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
- test/jestEnv.js
> fix: add analytics metadata DDB table Arn parameter to Redshift stack

- src/analytics/private/sqls/redshift/sp-scan-metadata.sql
----
Add the value type into property name to cover same parameter and different value type.
Otherwise, there will be the same primary key during lambda persist the metadata into ddb.
Add the value type into property name to cover same parameter and different value type
> chore: add the value type into property name to cover same parameter and different value type

- frontend/src/pages/pipelines/detail/comps/Processing.tsx
> fix: i18n analyticEngine uses wrong key

- frontend/src/apis/analytics.ts
- frontend/src/pages/analytics/metadata/event-parameters/MetadataParameterSplitPanel.tsx
- src/control-plane/backend/lambda/api/model/metadata.ts
- src/control-plane/backend/lambda/api/service/display.ts
- src/control-plane/backend/lambda/api/service/metadata.ts
- src/control-plane/backend/lambda/api/test/api/metadata.test.ts
> fix: hide value type as parameter suffix

- src/control-plane/backend/lambda/api/service/stack.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
> fix: pipeline inconsistent status when rollback complete

- src/analytics/lambdas/clear-expired-events-workflow/check-clear-status.ts
- src/analytics/lambdas/clear-expired-events-workflow/clear-expired-events.ts
- src/analytics/lambdas/custom-resource/get-source-prefix.ts
- src/analytics/parameter.ts
- src/analytics/private/metrics-common-workflow.ts
- src/analytics/private/sql-def.ts
- src/analytics/private/sqls/redshift/clickstream-log.sql
- src/analytics/private/sqls/redshift/sp-clear-expired-events.sql
- src/analytics/private/sqls/redshift/sp-clear-item-and-user.sql
- src/analytics/private/sqls/redshift/sp-clickstream-log.sql
- src/analytics/private/sqls/redshift/sp-scan-metadata.sql
- src/analytics/private/sqls/redshift/sp-upsert-users.sql
- src/metrics/util.ts
- test/analytics/analytics-on-redshift/lambda/clear-expire-events/clear-expire-events.test.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/get-source-prefix.test.ts
close https://github.com/awslabs/clickstream-analytics-on-aws/issues/289
----
- fix https://github.com/awslabs/clickstream-analytics-on-aws/issues/289
- fix upgrade error for alarm 'Clickstream|test_project_007 Max file age d9170ff0 already exists'
- fix upgrade error for s3 prefix of ods events files from control plane
> fix: clear expired events workflow execution faild

- src/common/constant.ts
- src/control-plane/backend/config/dictionary.json
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/data-pipeline/parameter.ts
----
- set default value TransformerAndEnrichClassNames from empty to `software.aws.solution.clickstream.TransformerV2,software.aws.solution.clickstream.UAEnrichment,software.aws.solution.clickstream.IPEnrichment`
- As PR: https://github.com/awslabs/clickstream-analytics-on-aws/pull/295, only change the default value of TransformerAndEnrichClassNames in `data processing` will not work if upgrading from old version. We also need to change the default value in control plane
> fix: change the default of TransformerAndEnrichClassNames in control plane

- src/analytics/lambdas/custom-resource/create-schemas.ts
- src/analytics/private/constant.ts
- src/analytics/private/model.ts
- src/analytics/private/sql-def.ts
- src/analytics/private/sqls/redshift/sp-clear-expired-events.sql
- src/analytics/private/sqls/redshift/sp-clear-item-and-user.sql
- src/analytics/private/sqls/redshift/sp-clickstream-log-non-atomic.sql
- src/analytics/private/sqls/redshift/sp-scan-metadata.sql
- src/analytics/private/sqls/redshift/sp-upsert-users.sql
- src/analytics/private/sqls/redshift/user-m-view.sql
- src/analytics/private/sqls/redshift/user.sql
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
----
1. change to exec bash sqls by appId
2. remove non-atomic from sp_scan_metadata
3. add a new sp_clickstream_log_non_atomic
> fix: execute bash sqls validation error in redshift when having several applications

- docs/en/sdk-manual/wechat.md
- docs/mkdocs.en.yml
- docs/mkdocs.zh.yml
- docs/zh/sdk-manual/wechat.md
> docs: add wechat SDK manual

- frontend/package.json
- frontend/yarn.lock
> chore(deps): bump resolve-url-loader from 4.0.0 to 5.0.0

- src/ingestion-server/server/private/ecs-cluster.ts
- test/ingestion-server/server/ingestion-server.test.ts
----
Force to use IMDSv2 in EC2 managed by ECS for ingestion server
close #141 
1. Force to use IMDSv2 in EC2 managed by ECS for ingestion server
2. Add unit test
> chore: force to use IMDSv2 in EC2 managed by ECS for ingestion server

- src/analytics/lambdas/scan-metadata-workflow/store-metadata-into-ddb.ts
- src/analytics/private/sqls/redshift/sp-scan-metadata.sql
- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/model/metadata.ts
- src/control-plane/backend/lambda/api/test/api/metadata.test.ts
- test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/store-metadata-into-ddb.test.ts
----
handle the case that user attribute value is empty and read user attribute hasData from summary
1. Handle the case that user attribute value is empty.
2. Add hasData field into summary for user attribute metadata.
3. Read user attribute hasData from summary.
> fix: handle the case that user attribute value is empty and read user attribute hasData from summary

- .github/workflows/dist-scan.yml
----
Specify cfn-lint version as 0.81.0, because 0.82.0 version caused error.
Already cut issue to track this 0.82.0 issue.  [cfn-lint issue](https://github.com/aws-cloudformation/cfn-lint/issues/2914)
> chore: specify cfn-lint version as 0.81.0

- .github/workflows/build.yml
- .github/workflows/dist-scan.yml
- .projenrc.js
> chore: specify the runner of build via variables

- src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
- src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
----
fix hard code 'app1' as event_parameter table schema.
> fix: hardcode database schema name when join event_parameter table

- src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
- src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
----
add user_pseudo_id as PARTITION BY key
filter sequence that not start from first specified event/node
> fix: missing partition by key user_pseudo_id

- src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/TransformerV2.java
- src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/BaseSparkTest.java
----
the test datasets where filtered by below keep days. 
```
System.setProperty(USER_KEEP_DAYS_PROP, String.valueOf(180));
System.setProperty(ITEM_KEEP_DAYS_PROP, String.valueOf(180));
```
change these two values to 356 * 100, 100 years.
> fix: ETL spark UT failure

- src/control-plane/backend/lambda/api/test/api/metadata.test.ts
----
Add ut case to cover without data in last day for metadata
Add ut case to cover without data in last day for metadata
> tests: add case for no data in last day in metadata

- src/analytics/private/sqls/redshift/event-parameter.sql
----
close https://github.com/awslabs/clickstream-analytics-on-aws/issues/344
> fix: change event_param_string_value to VARCHAR(4096)

- src/control-plane/backend/config/dictionary.json
- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/model/metadata.ts
- src/control-plane/backend/lambda/api/service/display.ts
- src/control-plane/backend/lambda/api/service/metadata.ts
- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
- src/control-plane/backend/lambda/api/test/api/metadata.test.ts
> feat: show built-in metadata when no data in DDB

- src/analytics/lambdas/custom-resource/create-schemas.ts
- src/analytics/private/sql-def.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
----
fix fail when update clickstream_session_view
verify the fix for #172 in #332
> fix: add app failure when update session view

- src/analytics/lambdas/custom-resource/create-schemas.ts
- src/control-plane/backend/Dockerfile
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
----
1. Wrong title of QuickSight visuals
2. Missing select permission on base tables 
> fix: wrong title of QuickSight visual

- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
> fix: DDB ExpressionAttributeValues empty error

- frontend/package.json
- frontend/yarn.lock
> fix: empty embedding QuickSight iframe

- frontend/package.json
- frontend/src/pages/analytics/comps/ExploreEmbedFrame.tsx
- frontend/yarn.lock
----
related to amazon-quicksight-embedding-sdk [issue](https://github.com/awslabs/amazon-quicksight-embedding-sdk/issues/170) 
> chore: Explicitly set the height/width for embedding-sdk 2.4.0

- frontend/public/locales/en-US/pipeline.json
- frontend/public/locales/zh-CN/pipeline.json
- frontend/src/apis/resource.ts
- frontend/src/pages/analytics/dashboard/create/CreateDashboard.tsx
- frontend/src/pages/pipelines/create/CreatePipeline.tsx
- frontend/src/pages/pipelines/create/steps/Reporting.tsx
- frontend/src/pages/pipelines/detail/comps/Reporting.tsx
- frontend/src/ts/init.ts
- frontend/src/types/analytics.d.ts
- frontend/src/types/pipeline.d.ts
- frontend/src/types/resources.d.ts
- frontend/test/msk-redshift.test.tsx
- frontend/test/service-available.test.tsx
- frontend/test/update-pipeline.test.tsx
- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/router/project.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
- src/reporting/lambda/custom-resource/quicksight/index.ts
- test/jestEnv.js
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
----
1. Frontend: delete **QuickSight user** select in last step when create pipeline.
2. Backend: create two user (**PublishUser**, **ExploreUser**).
3. Preset dashboard and dashboards that management by control-plane are create at PublishUser.
4. Explore dashboards are create at ExploreUser.
> feat: Reassign QuickSight users (PublishUser, ExploreUser)

- src/control-plane/backend/lambda/sfn-action/index.ts
- test/control-plane/lambda/sfn-action.test.ts
> chore: rollback stack with RetainExceptOnCreate

- examples/standalone-data-generator/send_event.py
- examples/standalone-data-generator/send_event_real_time.py
----
1. fix the value of compression in query parameters
> fix: compression value in query parameters in example generator

- src/control-plane/backend/lambda/api/i18n.ts
> fix: missing i18n string in backend

- frontend/src/pages/analytics/comps/ExploreEmbedFrame.tsx
- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/test/api/reporting.test.ts
Occasional situation where embedded explore dashboard cannot be open. Wait explore dashboard status SUCCESS before create embedding URL.
> fix: embedded explore dashboard cannot be open

- src/analytics/analytics-on-redshift.ts
- src/analytics/lambdas/scan-metadata-workflow/check-metadata-workflow-start.ts
- src/analytics/lambdas/scan-metadata-workflow/scan-metadata.ts
- src/analytics/lambdas/scan-metadata-workflow/store-metadata-into-ddb.ts
- src/analytics/lambdas/scan-metadata-workflow/update-workflow-info.ts
- src/analytics/parameter.ts
- src/analytics/private/constant.ts
- src/analytics/private/metrics-common-workflow.ts
- src/analytics/private/metrics-redshift-cluster.ts
- src/analytics/private/metrics-redshift-serverless.ts
- src/analytics/private/model.ts
- src/analytics/private/scan-metadata-workflow.ts
- src/analytics/private/sqls/redshift/sp-scan-metadata.sql
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
- src/data-analytics-redshift-stack.ts
- src/data-pipeline/utils/utils-common.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
- test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/check-workflow-start.test.ts
- test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/scan-metadata.test.ts
- test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/update-workflow-info.test.ts
- test/jestEnv.js
----
Refactor scan metadata feature.
Refactor scan metadata feature:
1. Scan metadata workflow is triggered from upstream workflow.  Upstream workflow change is in #361 
2. Check last time of job execution, trigger workflow if more than 24 hours have passed since the last job execution.
3. If workflow is triggered manually, can set scan start date as below:
```
{
"startScanDate": "2023-10-02"
}
```
4. @tyyzqmf  Store the Metadata summary into ddb per project, example as below:
```
{
"id": {
"S": "PROJECT_SUMMARY#projectId"
},
"month": {
"S": "#000000"
},
"lastJobStartTimestamp": {
"N": "1698416223647"
},
"latestScanDate": {
"S": "2023-10-27T00:00:00.000Z"
}
}
```
5. Add …
> chore: refactor metadata scanning

- .github/workflows/dist-scan.yml
----
Using latest cfn-lint version and suppress W3005
> chore: using latest cfn-lint version

- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/test/api/project.test.ts
> fix: handle with edge case of removing dashboards that dashboards were deleted out of solution

- src/analytics/private/sqls/redshift/sp-scan-metadata.sql
----
fix typo in scan metadata sql
fix typo in scan metadata sql
> fix: remove hardcode schema in scan metadata sql

- deployment/build-s3-dist.sh
> ci: fix the backend zip package and template prefix in dict in pipeline

- docs/en/sdk-manual/android.md
- docs/en/sdk-manual/swift.md
- docs/zh/sdk-manual/android.md
- docs/zh/sdk-manual/swift.md
----
1. add disable and enable in android and swift sdk manual
> docs: add disable and enable in android and swift sdk manual

- src/analytics/lambdas/load-data-workflow/check-load-status.ts
- src/analytics/lambdas/load-data-workflow/create-load-manifest.ts
- src/analytics/lambdas/load-data-workflow/load-manifest-to-redshift.ts
- src/analytics/lambdas/load-data-workflow/skip-running-workflow.ts
- src/analytics/private/load-ods-data-workflow.ts
- src/analytics/private/model.ts
- test/analytics/analytics-on-redshift/lambda/load-data/check-load-status.test.ts
- test/analytics/analytics-on-redshift/lambda/load-data/create-manifest.test.ts
- test/analytics/analytics-on-redshift/lambda/load-data/load-manifest-to-redshift.test.ts
- test/analytics/analytics-on-redshift/lambda/load-data/skip-running-workflow.test.ts
close https://github.com/awslabs/clickstream-analytics-on-aws/issues/412
----
1. fix: https://github.com/awslabs/clickstream-analytics-on-aws/issues/412
2. skip triggering scan meta workflow when no files to be loaded
> fix: load data to redshift error: conflict with concurrent transaction

- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/test/api/reporting.test.ts
> chore: clean tmp analysis filter with status

- src/analytics/private/app-schema.ts
- src/analytics/private/model.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
…change
----
Fix the issue that schema cannot be updated if there is no parameter change
Fix the issue that schema cannot be updated if there is no parameter change
> fix: updatable sql scripts are not executed when upgrading the data modeling stack

- src/analytics/lambdas/custom-resource/create-schemas.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
> fix: missing create new view when upgrade from 1.0.x

- .viperlightignore
- src/control-plane/backend/lambda/api/common/stack-params-valid.ts
- src/control-plane/backend/lambda/api/store/aws/ec2.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow.test.ts
----
1. Check NAT is create in **private subnet** or `ConnectivityType=private`
2. Check VPC Endpoint even if NAT already exists in private subnet
> chore: validate non-working network configuration

- src/control-plane/backend/click-stream-api.ts
- test/control-plane/click-stream-api.test.ts
> fix: ignore create role for quicksight embedding in china regions

- src/common/solution-info.ts
- src/control-plane/backend/stack-action-state-machine-construct.ts
- src/service-catalog-appregistry-stack.ts
- test/common/solution-info.test.ts
- test/control-plane/click-stream-api.test.ts
----
* Create service linked role for Service Catalog AppRegistry
* Use short version (e.g., v1.1.0) in Service Catalog AppRegistry application tag
> fix: create service linked role for Service Catalog AppRegistry

- src/control-plane/backend/click-stream-api.ts
- test/control-plane/click-stream-api.test.ts
> fix: miss permission for ec2 DescribeNatGateways

- src/common/solution-info.ts
- src/control-plane/backend/stack-action-state-machine-construct.ts
- test/control-plane/click-stream-api.test.ts
----
Add `servicecatalog:UpdateApplication` permission for api role
> fix: add servicecatalog:UpdateApplication for api role

- frontend/public/locales/en-US/user.json
- frontend/public/locales/zh-CN/user.json
- frontend/src/AppRouter.tsx
- frontend/src/components/layouts/AnalyticsNavigation.tsx
- frontend/src/pages/analytics/comps/DashboardHeader.tsx
- frontend/src/pages/analytics/event/AnalyticsEvent.tsx
- frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
- frontend/src/pages/analytics/metadata/event-parameters/MetadataParameterSplitPanel.tsx
- frontend/src/pages/analytics/metadata/event-parameters/MetadataParametersTable.tsx
- frontend/src/pages/analytics/metadata/events/MetadataEventSplitPanel.tsx
- frontend/src/pages/analytics/metadata/events/MetadataEventsTable.tsx
- frontend/src/pages/analytics/metadata/table/MetadataDictionaryTable.tsx
- frontend/src/pages/analytics/metadata/user-attributes/MetadataUserAttributeSplitPanel.tsx
- frontend/src/pages/analytics/metadata/user-attributes/MetadataUserAttributesTable.tsx
- frontend/src/pages/analytics/path/AnalyticsPath.tsx
- frontend/src/pages/analytics/retention/AnalyticsRetention.tsx
- frontend/src/pages/user/CreateUser.tsx
- frontend/src/pages/user/SettingUser.tsx
- frontend/src/pages/user/UserList.tsx
- frontend/src/ts/const.ts
- frontend/src/types/user.ts
- src/control-plane/backend/lambda/api/common/constants.ts
- src/control-plane/backend/lambda/api/common/types.ts
- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/middle-ware/auth-role.ts
- src/control-plane/backend/lambda/api/model/user.ts
- src/control-plane/backend/lambda/api/service/user.ts
- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
- src/control-plane/backend/lambda/api/test/api/auth.test.ts
- src/control-plane/backend/lambda/api/test/api/user.test.ts
----
1. Backend api auth add analyst reader role
2. User settings support set analyst reader group in cognito
3. Frontend hide Analyse menu if current user is analyst reader
4. Disable edit metadata display name and description if current user is analyst reader
> feat: add new role AnalystReader

- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
> fix: reporting stack miss parameter

- src/cloudfront-control-plane-stack.ts
- test/control-plane/cloudfront-control-plane-stack.test.ts
----
set InstallLatestAwsSdk to false in china regions
> fix: control plane deploy fail in CN regions

- frontend/src/apis/user.ts
- src/control-plane/backend/lambda/api/test/api/user.test.ts
> fix: user api encode uid

- src/analytics/private/sqls/redshift/dashboard/clickstream_user_dim_view_v1.sql
- src/data-reporting-quicksight-stack.ts
- src/reporting/lambda/custom-resource/quicksight/index.ts
- src/reporting/private/dashboard.ts
- src/reporting/private/dataset-col-def.ts
- src/reporting/private/iam.ts
- src/reporting/private/template-def.json
- src/reporting/quicksight-custom-resource.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
----
append latest template version to template Arn when update dashboard
> fix: Cannot access data for this visual in dashboard

- src/control-plane/backend/click-stream-api.ts
- src/control-plane/backend/lambda/api/model/stacks.ts
- test/control-plane/click-stream-api.test.ts
> fix: QuickSight subscription check error when creating/updating reporting

- src/control-plane/backend/lambda/api/common/constants.ts
- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/index.ts
- src/control-plane/backend/lambda/api/middle-ware/inject-context.ts
- src/control-plane/backend/layer/lambda-web-adapter/layer.ts
----
1. Upgrade LambdaAdapter default version to 0.7.1 for support lambda context.
2. Inject context IDs to log attribute.
3. Add new response header `X-Click-Stream-Lambda-Request-Id`
> chore: Correlate API Gateway request ID with Lambda request ID

- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/service/user.ts
- src/control-plane/backend/lambda/api/test/api/user.test.ts
> fix: user settings miss attributes in ddb

- src/analytics/lambdas/custom-resource/redshift-associate-iam-role.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/redshift-associate-iam-role.test.ts
----
Can parse the IamRole string of Redshift Serverless namespace in different outputs in recent changes,
1. IamRole(applyStatus=in-sync, iamRoleArn=arn:aws:iam::123456789:role/Clickstream-DataModelingR-CopyDataFromS3Role8483EDC-2EpRGwygJTu3)
2. IamRole(iamRoleArn=arn:aws:iam::1234567890:role/Clickstream-DataModelingR-CopyDataFromS3Role8483EDC-Phl68sLxbG85, applyStatus=in-sync)
closes #504
> chore: parse the IamRole of redshift serverless namespace with different outputs

- .viperlightignore
- frontend/src/ts/request.ts
- frontend/src/ts/test/utils.test.ts
- frontend/src/ts/utils.ts
- src/control-plane/backend/lambda/api/middle-ware/response-time.ts
- src/control-plane/backend/lambda/api/router/user.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/store/click-stream-store.ts
- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
- src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
- src/control-plane/backend/lambda/api/test/api/application.test.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
- src/control-plane/backend/lambda/api/test/api/plugin.test.ts
- src/control-plane/backend/lambda/api/test/api/project.test.ts
- src/control-plane/backend/lambda/api/test/api/request-id.test.ts
- src/control-plane/backend/lambda/api/test/api/user.test.ts
> fix: using same request id when sending concurrent requests

- examples/standalone-data-generator/application/shopping/ScreenEvent.py
- examples/standalone-data-generator/application/shopping/ShoppingScreen.py
----
1. change example data generator live max count to 4
> fix: example data generator live count

- frontend/src/pages/pipelines/create/CreatePipeline.tsx
- frontend/src/ts/utils.ts
> fix: set warm pool default value to 0 when pipeline update

- src/analytics/lambdas/scan-metadata-workflow/check-metadata-workflow-start.ts
- src/analytics/private/scan-metadata-workflow.ts
- test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/check-workflow-start.test.ts
> chore: check previous scan metadata workflow job is running

- src/common/constant.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/store/aws/redshift.ts
- src/control-plane/backend/lambda/api/test/api/env.test.ts
----
1. Enable Redshift Serverless in cn-north-1
2. Disable QuickSight in China region
> chore: service ping in China region

- src/control-plane/backend/lambda/api/locales/en-US.json
> fix: limit time filter hint text to max length 100

- src/control-plane/backend/lambda/api/service/display.ts
- src/control-plane/backend/lambda/api/test/api/metadata.test.ts
> fix: custom display overwrite preset display

- src/control-plane/backend/lambda/api/common/stack-params-valid.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
> fix: upgrade pipeline with empty reporting object

- src/reporting/private/template-def.json
> fix: update builtin dashboard end date filter default value to current day

- src/data-reporting-quicksight-stack.ts
- src/reporting/lambda/custom-resource/quicksight/index.ts
- src/reporting/private/dashboard.ts
- src/reporting/private/iam.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
> fix: data source update fail when upgrade from v1.0.3

- src/analytics/lambdas/custom-resource/create-schemas.ts
- src/analytics/lambdas/redshift-data.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
- test/jestEnv.js
> fix: properly handle with the timeout while waiting for redshift data execution result

- src/control-plane/backend/click-stream-api.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/test/api/project.test.ts
- test/control-plane/click-stream-api.test.ts
> chore: delete QuickSight user when delete last one project

- src/metrics/add-sns-subscription.ts
- src/metrics/custom-resource/add-sns-subscription/index.ts
- test/metrics/add-sns-subscription.test.ts
> fix: duplicated subscription emails in metrics when upgrade pipeline

- frontend/src/pages/analytics/dashboard/create/CreateDashboard.tsx
- frontend/src/types/analytics.d.ts
- src/control-plane/backend/lambda/api/model/project.ts
- src/control-plane/backend/lambda/api/router/project.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
- src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
> chore: remove data source ARN and owner principal in create dashboard api

- docs/en/pipeline-mgmt/ingestion/create-data-sink-w-kafka.md
- docs/zh/pipeline-mgmt/ingestion/create-data-sink-w-kafka.md
----
add self-hosted kafka cluster part
add self-hosted kafka cluster part
> docs: add self-hosted kafka cluster

- src/control-plane/backend/lambda/api/common/request-valid.ts
- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
> chore: validate the ingress rules of security groups of vpc endpoints

- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/test/api/project.test.ts
> fix: able to delete project when it status is failed

- frontend/public/locales/en-US/application.json
- frontend/public/locales/zh-CN/application.json
- frontend/src/pages/application/create/comp/RegisterApp.tsx
- frontend/src/pages/application/detail/ApplicationDetail.tsx
- frontend/src/pages/application/detail/comp/ConfigFlutterSDK.tsx
- frontend/src/ts/guideConst.ts
> fix: add integrate flutter SDK guide in application detail page

- frontend/public/locales/en-US/analytics.json
- frontend/public/locales/zh-CN/analytics.json
- frontend/src/apis/analytics.ts
- frontend/src/components/eventselect/AnalyticsType.ts
- frontend/src/components/layouts/AnalyticsHeader.tsx
- frontend/src/context/reducer.ts
- frontend/src/index.scss
- frontend/src/pages/analytics/AnalyticsHome.tsx
- frontend/src/pages/analytics/analyzes/AnalyticsAnalyzes.tsx
- frontend/src/pages/analytics/comps/ExploreEmbedFrame.tsx
- frontend/src/pages/analytics/dashboard/AnalyticsDashboard.tsx
- frontend/src/pages/analytics/dashboard/create/CreateDashboard.tsx
- frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
- frontend/src/pages/analytics/metadata/table/MetadataTable.tsx
- frontend/src/ts/utils.ts
- frontend/src/types/pipeline.d.ts
- frontend/src/types/project.d.ts
- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/model/project.ts
- src/control-plane/backend/lambda/api/router/reporting.ts
- src/control-plane/backend/lambda/api/service/pipeline.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
- src/control-plane/backend/lambda/api/test/api/project.test.ts
----
1. Access Analytics Studio when no pipeline in solution 
2. Access Analytics Studio when pipeline version is `v1.0.x` 
3. Access Analytics Studio when project or app no exist
> chore: improve UX for Analytics Studio when pipeline not support

- src/control-plane/backend/lambda/api/service/user.ts
- src/control-plane/backend/lambda/api/test/api/user.test.ts
> fix: disallow to delete system user that created by solution

- frontend/src/pages/pipelines/create/CreatePipeline.tsx
- frontend/src/pages/pipelines/create/steps/Reporting.tsx
> fix: disable next when QuickSight not subscribe in create pipeline

- src/control-plane/backend/lambda/api/router/user.ts
- src/control-plane/backend/lambda/api/test/api/user.test.ts
> fix: check XSS in update user api

- examples/standalone-data-generator/configure.py
- examples/standalone-data-generator/create_event.py
----
1. change default app type to shopping in example data generator
> chore: change default app type to shopping in example data generator

- examples/standalone-data-generator/configure.py
----
1. support example data generator run in other path
> chore: support example data generator run in other path

- docs/en/pipeline-mgmt/ingestion/configure-ingestion-endpoint.md
- docs/zh/pipeline-mgmt/ingestion/configure-ingestion-endpoint.md
----
update doc for ingestion auth example
update doc for ingestion auth example
> docs: add notes for ingestion auth client example

- src/reporting/lambda/custom-resource/quicksight/index.ts
- src/reporting/private/dashboard.ts
- src/reporting/quicksight-custom-resource.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
> fix: QuickSight dataset parameter default value

- src/reporting/lambda/custom-resource/quicksight/index.ts
- src/reporting/private/dashboard.ts
- src/reporting/quicksight-custom-resource.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
> fix: QuickSight dataset parameter default value (#687)

- src/control-plane/cloudfront-s3-portal.ts
- test/control-plane/cloudfront-s3-portal.test.ts
> fix: CloudFront resource name with region suffix

- src/data-reporting-quicksight-stack.ts
- src/reporting/lambda/custom-resource/quicksight/network-interface-check.ts
- src/reporting/network-interface-check-custom-resource.ts
- src/reporting/private/dashboard.ts
- src/reporting/private/iam.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
- test/reporting/quicksight/lambda/network-interface-check.test.ts
> fix: intermitent failure of creating data source of QuickSight

- src/cloudfront-control-plane-stack.ts
- src/control-plane/cloudfront-s3-portal.ts
- test/control-plane/cloudfront-control-plane-stack.test.ts
- test/control-plane/cloudfront-s3-portal.test.ts
> chore: add cache control to web console files not to cache index html

- src/ingestion-server/custom-resource/update-alb-rules/index.ts
- test/ingestion-server/custom-resource/update-alb-rules.test.ts
----
Support updating domain name, endpoint path and auth secret arn
1, Support updating 
- domain name
- endpoint path
- auth secret arn
2, Add unit test cases for above changes
1, third sdk + http
- change endpoint path
- add appId
- change endpoint path again
2, third sdk + https + disable auth
- change endpoint path
- add appId
- change endpoint path again
3, third sdk, https, enable auth
- change auth arn
- change domain
- change endpoint path
- change above together
- add appId
4, clickstream sdk + http
- change endpoint path
- add appId
- change endpoint path again
- add and remove appId
5, clickstream sdk + https + disable auth
- change endpoint path
- change domain …
> fix: support updating domain, endpoint path and auth secret of ingestion server

- src/ingestion-server/custom-resource/update-alb-rules/index.ts
- test/ingestion-server/custom-resource/update-alb-rules.test.ts
…ion server (#706)
----
support updating domain, endpoint path and auth secret of ingestion
support updating domain, endpoint path and auth secret of ingestion
> fix: support updating domain, endpoint path and auth secret of ingestion

- docs/en/troubleshooting.md
- docs/en/upgrade.md
- docs/zh/troubleshooting.md
- docs/zh/upgrade.md
- src/analytics/lambdas/custom-resource/create-schemas.ts
- src/analytics/lambdas/redshift-data.ts
- src/analytics/private/app-schema.ts
- src/analytics/private/model.ts
- src/analytics/private/sql-def.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
----
1. add doc how to handle upgrade  issue 'UPDATE_ROLLBACK_FAILED ' from v1.0.x to v1.1.x
2. remove `updatable` flag for sql file, simplify the update/upgrade logic
3. change exec SQL one by one, not batch
4. ignore SQL error: `xxxx already exists` when apply SQL
5. add env `SUPPRESS_DB_ERROR` and `SUPPRESS_ALL_ERROR` to lambda `CreateSchemaForApplicationsFn` to handle further upgrade issue
> fix: redshift stack upgrade issue in UPDATE_ROLLBACK_FAILED

- src/analytics/lambdas/custom-resource/create-schemas.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
----
1. when update the cloudFormation,  comparing new lastModifiedTime and old lastModifiedTime of the SQL files
- if equal, only create schema for new added appIds
- if not equal, re-apply sql files for all appIds
2. apply sql for different appIds in parallel if update/create multi appIds in the same time
> fix: create app schema timeout when appId count more than 15

- src/ingestion-server/server/images/vector/Dockerfile
----
upgrade vector to 0.34.1 version
upgrade vector to 0.34.1 version
Test below cases:
1, Ingestion => S3
2, Ingestion => KDS on demand
3, Ingestion => MSK
> chore: upgrade vector to 0.34.1

- src/analytics/lambdas/scan-metadata-workflow/scan-metadata.ts
- src/analytics/private/constant.ts
----
fix the issue of delete scan metadata data log](fix: fix the issue that the clickstream_log of scan metadata cannot be deleted
fix the issue of delete scan metadata data log](fix: fix the issue that the clickstream_log of scan metadata cannot be deleted
> fix: use wrong store procedure name when cleaning logs of scanning metadata

- src/analytics/analytics-on-redshift.ts
- src/analytics/lambdas/custom-resource/create-redshift-namespace.ts
- src/analytics/lambdas/custom-resource/redshift-associate-iam-role.ts
- src/analytics/lambdas/load-data-workflow/refresh-views.ts
- src/analytics/lambdas/redshift-data.ts
- src/analytics/private/model.ts
- src/analytics/private/redshift-associate-iam-role.ts
- src/common/utils.ts
- src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/ingestion-server/custom-resource/delete-ecs-cluster/index.ts
- src/ingestion-server/kafka-s3-connector/custom-resource/kafka-s3-sink-connector/index.ts
- src/reporting/lambda/custom-resource/quicksight/index.ts
- src/reporting/lambda/custom-resource/quicksight/network-interface-check.ts
- test/ingestion-server/kafka-s3-connector/custom-resource/kafka-s3-sink-connector.test.ts
> chore: refactor Redshift associate IAM roles as construct

- src/analytics/private/redshift-associate-iam-role.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
----
Redshift Serverless does not have a service-link role, we can not pass the roles with a conditional service name. Only specify the condition when associating roles to a Redshift provisioned cluster.
> fix: only specify the pass role condition for provisioned redshift

- src/analytics/private/app-schema.ts
- src/data-analytics-redshift-stack.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
> fix: specify wrong bi user parameter for custom resource

- src/control-plane/backend/Dockerfile
> fix: prune node_modules to reduce api lambda size

- src/analytics/analytics-on-redshift.ts
- src/analytics/private/metrics-common-workflow.ts
- src/analytics/private/metrics-redshift-cluster.ts
- src/analytics/private/metrics-redshift-serverless.ts
- src/metrics/custom-resource/get-interval/index.ts
- src/metrics/get-interval-custom-resource.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
- test/metrics/get-interval.test.ts
----
set scan metadata data workflow alarm period as 1 day
set scan metadata data workflow alarm period as 1 day
change test cases to cover change.
> fix: set scan metadata data workflow alarm period with stack parameter

- frontend/src/pages/pipelines/create/CreatePipeline.tsx
- src/control-plane/backend/lambda/api/store/aws/s3.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow.test.ts
----
1. fix bucket check in backend.
2. clear selected bucket when region changed.
> fix: incorrectly choose or input s3 bucket in another region

- frontend/public/locales/en-US/pipeline.json
- frontend/public/locales/zh-CN/pipeline.json
- frontend/src/pages/pipelines/comps/BasicInfo.tsx
- frontend/src/pages/pipelines/create/CreatePipeline.tsx
- frontend/src/pages/pipelines/create/steps/BasicInformation.tsx
- src/control-plane/backend/lambda/api/service/pipeline.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
----
1. validate tags empty key and value
2. return empty object if dataProcessing disable 
> fix: validate tags empty key and value

- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/store/aws/cloudformation.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-status.test.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
----
1. creating pipeline error status when refresh force
Reorganize the status pseudocode：
Algorithm get-pipeline-status is:
&nbsp;&nbsp;&nbsp;&nbsp;Retrieve `latestAction`: Create, Update, Delete
&nbsp;&nbsp;&nbsp;&nbsp;Retrieve `stackStatus`
&nbsp;&nbsp;&nbsp;&nbsp;Retrieve `executionStatus`
&nbsp;&nbsp;&nbsp;&nbsp;**If** executionStatus **failed**:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**return** FAILED
&nbsp;&nbsp;&nbsp;&nbsp;**ElseIf** executionStatus is **running**:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**return** pipeline status is Updating, Creating or Deleting depending on latestAction
&nbsp;&nbsp;&nbsp;&nbsp;**ElseIf** executionStatus is …
> fix: creating pipeline error status when refresh force

- src/analytics/private/app-schema.ts
- src/data-analytics-redshift-stack.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
> fix: specify wrong bi user parameter for custom resource parameter

- src/control-plane/backend/stack-action-state-machine-construct.ts
- test/control-plane/click-stream-api.test.ts
> fix: add ListRoleTags permission for tagging IAM roles

- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/store/aws/events.ts
- src/control-plane/backend/lambda/api/store/aws/sns.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
----
When creating duplicate resources with the same name, they cannot have different tags.
> fix: upgrade pipeline failed because create topic and rule 

- src/reporting/lambda/custom-resource/quicksight/index.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
----
grant permissions to publish user, let user can create new dataset based on this datasource
> fix: datasource is not appearing on the Console Analyzes UI

- src/analytics/private/metrics-common-workflow.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
----
enable scan metadata alarm actions
enable scan metadata alarm actions
> fix: enable scan metadata alarm actions

- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/service/stack.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
> fix: update pipeline when QuickSight already existed

- src/control-plane/backend/lambda/listen-stack-status/index.ts
- src/control-plane/backend/lambda/listen-stack-status/listen-tools.ts
- src/control-plane/backend/lambda/listen-state-status/index.ts
- test/control-plane/lambda/listen-stack-status.test.ts
- test/control-plane/lambda/listen-state-status.test.ts
> fix: update pipeline status with optimistic locking

- src/control-plane/backend/lambda/api/service/metadata.ts
- src/control-plane/backend/lambda/api/test/api/metadata.test.ts
> fix: scan metadata when status is undefined

- src/control-plane/backend/batch-insert-ddb-custom-resource-construct.ts
- src/control-plane/backend/lambda/batch-insert-ddb/index.ts
- test/control-plane/lambda/batch-insert-ddb.test.ts
> fix: dictionary data not updated when Custom Resource parameters unchanged

- src/reporting/lambda/custom-resource/quicksight/index.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
> fix: can' t delete app when QuickSight folder contains customer resources

- src/control-plane/backend/lambda/api/common/stack-params-valid.ts
- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
> fix: do not create QuickSight user in China region

- src/ingestion-server/server/private/cfn-nag.ts
- src/main.ts
----
Add IngestionServerStackV2 into main.ts file
> fix: add IngestionServerStackV2 into main

- src/ingestion-server/server/images/nginx/config/nginx.conf
----
drop OPTIONS request in ingestion server
drop OPTIONS request in ingestion server
> chore: don't sink OPTIONS request in ingestion server

- src/data-pipeline/spark-etl/build.gradle
- src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/MaxLengthTransformer.java
- src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/gtm/ServerDataConverter.java
- src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/MaxLengthTransformerTest.java
> fix: make ETL compatible with Java 8

- src/analytics/lambdas/sql-execution-sfn/sql-execution-step-fn.ts
- test/analytics/analytics-on-redshift/lambda/sql-execution-sfn/sql-execution-sfn-provisioned.test.ts
- test/analytics/analytics-on-redshift/lambda/sql-execution-sfn/sql-execution-sfn-serverless.test.ts
> fix: sql error for provisioned redshift

- docs/en/sdk-manual/android.md
- docs/zh/sdk-manual/android.md
----
1. update default value for android SDK log event configuration
> docs: update default value for android SDK log event configuration

- src/ingestion-server/server/images/nginx/Dockerfile
----
use nginx user to start nginx server
> chore: use non-root user to start nginx

- src/analytics/lambdas/sql-execution-sfn/sql-execution-step-fn.ts
- test/analytics/analytics-on-redshift/lambda/sql-execution-sfn/sql-execution-sfn-provisioned.test.ts
- test/analytics/analytics-on-redshift/lambda/sql-execution-sfn/sql-execution-sfn-serverless.test.ts
----
v114 provision error
v114 provision error
> fix: fail to create schema in provisioned redshift

- src/control-plane/backend/stack-action-state-machine-construct.ts
- test/control-plane/click-stream-api.test.ts
----
Cherry-pick commit [#892](https://github.com/awslabs/clickstream-analytics-on-aws/pull/892/commits)
> fix: grant permissions for project deletion

- frontend/src/pages/analytics/analyzes/AnalyticsAnalyzes.tsx
- src/common/constant.ts
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/test/api/project.test.ts
- src/control-plane/backend/lambda/api/test/api/reporting.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
- src/reporting/lambda/custom-resource/quicksight/index.ts
- test/control-plane/click-stream-api.test.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
----
1. Remove QuickSight explore user
2. Create template dashboards in Publish user
3. Clean template dashboards when access analyses page 
> chore: remove QuickSight explore user

- src/control-plane/backend/stack-action-state-machine-construct.ts
- test/control-plane/click-stream-api.test.ts
> chore: add CloudFormation action for nested stacks

- frontend/public/locales/en-US/pipeline.json
- frontend/public/locales/zh-CN/pipeline.json
- frontend/src/apis/resource.ts
- frontend/src/pages/pipelines/create/CreatePipeline.tsx
- frontend/src/pages/pipelines/create/steps/ConfigIngestion.tsx
- frontend/src/pages/pipelines/create/steps/Reporting.tsx
- frontend/src/ts/init.ts
- frontend/src/ts/utils.ts
- frontend/src/types/pipeline.d.ts
- src/cloudfront-control-plane-stack.ts
- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/router/environment.ts
- src/control-plane/backend/lambda/api/service/environment.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/service/stack.ts
- src/control-plane/backend/lambda/api/store/aws/cloudformation.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/env.test.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
- src/control-plane/backend/lambda/api/test/api/reporting.test.ts
- src/reporting/lambda/custom-resource/quicksight/index.ts
- test/control-plane/click-stream-api.test.ts
- test/control-plane/cloudfront-control-plane-stack.test.ts
----
1. If it is the third step of creating pipelines in China regions, a user must be selected to create preset QuickSight resources. And global region unchanged.
2. Backend pass the selected user to reporting stack.
3. Analytics Studio embedding user change to the selected user in China regions.
> feat: onboard QuickSight in CN regions

- src/control-plane/backend/Dockerfile
- src/control-plane/frontend/Dockerfile
> fix: failure of building frontend image for web console deployment within vpc

- frontend/src/pages/pipelines/create/CreatePipeline.tsx
- frontend/src/pages/pipelines/create/steps/Reporting.tsx
- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-status.test.ts
- src/control-plane/backend/lambda/api/test/api/store.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
> fix: do not select QuickSight users when deploying in global regions

- deployment/build-s3-dist.sh
- deployment/solution_config
> chore: use env solution name as assets prefix in build-s3-dist

- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
- src/data-reporting-quicksight-stack.ts
- src/reporting/parameter.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
> fix: fail to upgrade existing pipeline to latest reporting stack

- src/reporting/lambda/custom-resource/quicksight/index.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
> fix: missing database name when update dataset

- src/reporting/parameter.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
> chore: remove duplicated database schema parameter in reporting stack

- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
> fix: assign wrong QuickSight user when editing existing pipeline created by previous version

- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
> fix: assign wrong QuickSight user when editing existing pipeline created by previous version 

- src/analytics/lambdas/load-data-workflow/check-load-status.ts
- src/analytics/lambdas/sql-execution-sfn/sql-execution-step-fn.ts
- src/analytics/private/sql-execution-workflow.ts
- src/common/workflow.ts
- test/analytics/analytics-on-redshift/lambda/sql-execution-sfn/sql-execution-sfn-provisioned.test.ts
- test/analytics/analytics-on-redshift/lambda/sql-execution-sfn/sql-execution-sfn-serverless.test.ts
- test/analytics/analytics-on-redshift/workflow/sql-execution-sfn.json
----
add backoff for sql execution
> chore: add backoff for sql execution

- src/analytics/lambdas/load-data-workflow/check-load-status.ts
- src/analytics/lambdas/sql-execution-sfn/sql-execution-step-fn.ts
- src/analytics/private/sql-exectution-stepfuncs.ts
- src/common/workflow.ts
- test/analytics/analytics-on-redshift/lambda/sql-execution-sfn/sql-execution-sfn-provisioned.test.ts
- test/analytics/analytics-on-redshift/lambda/sql-execution-sfn/sql-execution-sfn-serverless.test.ts
- test/analytics/analytics-on-redshift/workflow/sql-execution-sfn.json
----
add backoff for sql execution 
> chore: add backoff for sql execution 

- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/test/api/reporting.test.ts
> fix: do not delete explore user when pipeline versions contain v1.1.4

- src/reporting/lambda/custom-resource/quicksight/index.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
> fix: QuickSight stack update fail when shared database name not equals source database name

- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/service/pipeline.ts
- src/control-plane/backend/lambda/api/test/api/utils.test.ts
----
Filter out dynamic tags in pipeline detail page
> fix: filter out dynamic tags in pipeline detail page

- src/analytics/lambdas/load-data-workflow/check-load-status.ts
- src/analytics/lambdas/sql-execution-sfn/sql-execution-step-fn.ts
- src/common/workflow.ts
- test/analytics/analytics-on-redshift/lambda/load-data/check-load-status.test.ts
----
refactor time backoff to lambda decorator
refactor time backoff to lambda decorator
> chore: refactor time backoff to lambda decorator

- src/analytics/lambdas/load-data-workflow/create-load-manifest.ts
- test/analytics/analytics-on-redshift/lambda/load-data/create-manifest.test.ts
----
handle enqueue event
handle enqueue event
> fix: reload enqueue events

- src/analytics/lambdas/load-data-workflow/put-ods-source-to-store.ts
- src/analytics/private/load-ods-data-workflow.ts
- test/analytics/analytics-on-redshift/lambda/load-data/put-ods-source-to-store.test.ts
- test/jestEnv.js
----
exclude the files not belonged to ods data when enqueue into DDB
exclude the files not belonged to ods data when enqueue into DDB
> fix: exclude the files not belonged to ods data when enqueue into DDB

- src/analytics/lambdas/load-data-workflow/put-ods-source-to-store.ts
----
refactor exclude the files not belonged to ods data when enqueue into DDB
refactor exclude the files not belonged to ods data when enqueue into DDB
> chore: refactor exclude the files not belonged to ods data when enqueue into DDB

- src/ingestion-server/server/images/vector/config/vector.toml
----
handle upload_timestamp query parameter from client side
handle upload_timestamp query parameter from client side
> chore: handle upload_timestamp query parameter from client side

- src/analytics/lambdas/custom-resource/create-schemas.ts
- src/analytics/private/app-schema.ts
- src/analytics/private/model.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
- test/streaming-ingestion/streaming-ingestion-stack.test.ts
----
refactor sql script update according to hash code change
refactor sql script update according to hash code change
> chore: refactor sql script update according to hash code change

- src/data-pipeline/utils/utils-lambda.ts
- test/data-pipeline/data-pipeline-stack.test.ts
----
remove GlueTablePartition default concurrent executions config
> chore: remove GlueTablePartition default concurrent executions config

- src/data-pipeline/utils/utils-lambda.ts
- test/data-pipeline/data-pipeline-stack.test.ts
> chore: remove GlueTablePartition default concurrent executions

- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
> fix: the stack parameter for data rentention in Redshift not work

- src/streaming-ingestion-stack.ts
- test/streaming-ingestion/streaming-ingestion-stack.test.ts
> chore: add parameters for AppRegistry and role boundary

- src/streaming-ingestion/private/redshift-stack.ts
- test/streaming-ingestion/streaming-ingestion-stack.test.ts
> chore: remove role path for IAM role created in streaming stack

- examples/standalone-data-generator/application/shopping/ShoppingApp.py
----
1. fix example data generator user first touch timestamp
> chore: fix example data generator user first touch timestamp

- frontend/src/AppRouter.tsx
- frontend/src/AppSignInPage.tsx
- frontend/src/components/common/RoleRoute.tsx
- frontend/src/index.scss
- frontend/src/pages/error-page/ReSignIn.tsx
- frontend/src/ts/const.ts
----
All brand new session expire experience.
The code already renew the token by the OIDC configuration:
https://github.com/awslabs/clickstream-analytics-on-aws/blob/acf13f12f360980f2c4f9f3b5923aed1c656db33/frontend/src/App.tsx#L39
New session expire UI:
> chore: redirect the last visited page when user re-login

- src/reporting/lambda/custom-resource/quicksight/index.ts
- src/reporting/private/dashboard.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
> chore: remove analysis creation when creating dashboard

- .github/workflows/ghpage.yml
- docs/en/sdk-manual/android.md
- docs/en/sdk-manual/react-native.md
- docs/en/sdk-manual/swift.md
- docs/en/sdk-manual/web.md
- docs/zh/sdk-manual/android.md
- docs/zh/sdk-manual/react-native.md
- docs/zh/sdk-manual/swift.md
- docs/zh/sdk-manual/web.md
----
1. add record screen view events documentation for react navigation
2. add sample project link in SDK manual
> docs: add record screen views for react navigation in SDK manual

- docs/en/sdk-manual/flutter.md
- docs/zh/sdk-manual/flutter.md
- docs/zh/sdk-manual/react-native.md
----
1. add record screen view events in flutter SDK manual
> docs: add record screen view events in flutter SDK manual

- src/analytics/analytics-on-redshift.ts
- src/analytics/lambdas/custom-resource/create-schemas.ts
- src/analytics/private/app-schema.ts
- src/analytics/private/model.ts
- src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_view_cnt_mv.sql
- src/analytics/private/sqls/redshift/dashboard/clickstream_lifecycle_view_v2.sql
- src/analytics/private/sqls/redshift/dashboard/clickstream_retention_base_view.sql
- src/analytics/private/sqls/redshift/dashboard/clickstream_retention_user_new_return_sp.sql
- src/common/utils.ts
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow.test.ts
- src/data-reporting-quicksight-stack.ts
- src/reporting/lambda/custom-resource/quicksight/index.ts
- src/reporting/parameter.ts
- src/reporting/private/dashboard.ts
- src/reporting/quicksight-custom-resource.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
> chore(schema): reporting/model stack supports timezone setting for app

- src/analytics/lambdas/custom-resource/create-schemas.ts
- src/analytics/parameter.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
> fix(schema): redshift stack fail due to missing timezone

- src/ingestion-server/kafka-s3-connector/custom-resource.ts
- src/ingestion-server/kafka-s3-connector/custom-resource/kafka-s3-sink-connector/index.ts
- src/ingestion-server/kafka-s3-connector/iam.ts
- test/ingestion-server/kafka-s3-connector/custom-resource/kafka-s3-sink-connector.test.ts
- test/ingestion-server/kafka-s3-connector/kafka-s3-connector-stack.test.ts
----
add tags to kafka connector
add tags to kafka connector
> chore: add tags to kafka connector

- src/reporting/lambda/custom-resource/quicksight/index.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
> fix(schema): QuickSight stack deployment fail due to missing timeozone

- e2e-deploy.sh
> chore: e2e deploy script supports the parameter with json value

- src/control-plane/backend/lambda/sfn-workflow/index.ts
- test/control-plane/lambda/sfn-workflow.test.ts
> fix: stack information callback error when stack had been deleted

- src/alb-control-plane-stack.ts
- src/base-lib/src/constant/constant.ts
- src/cloudfront-control-plane-stack.ts
- src/common/parameters.ts
> chore: reorder the parameters of web console stacks

- src/analytics/lambdas/load-data-workflow/refresh-views.ts
- test/analytics/analytics-on-redshift/lambda/load-data/refresh-views.test.ts
- test/jestEnv.js
----
refresh date of previous day
> chore: calibrate refresh day when refreshing MVs

- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
> fix: version range of ClickstreamMetadataDdbArn

- src/analytics/lambdas/refresh-materialized-views-workflow/check-next-refresh-view.ts
- src/analytics/lambdas/refresh-materialized-views-workflow/check-refresh-sp-status.ts
- src/analytics/lambdas/refresh-materialized-views-workflow/check-refresh-workflow-start.ts
- src/analytics/lambdas/refresh-materialized-views-workflow/check-start-sp-refresh.ts
- src/analytics/private/refresh-materialized-views-workflow.ts
- test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/check-refresh-workflow-start.test.ts
- test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/check-start-sp-refresh.test.ts
----
fix refresh view issues
1. Add lambda TooManyRequestsException retry
2. fix issue of code checking
3. fix issue of check-refresh-sp-status.ts response
4. Checking existing workflow running
5. check max refresh date for each sp
> fix: edge cases of refresh view and improve stability

- buildspec.yml
- deployment/run-unit-tests.sh
- src/common/s3-asset.ts
- src/control-plane/backend/click-stream-api.ts
- src/control-plane/backend/layer/lambda-web-adapter/layer.ts
- src/control-plane/cloudfront-s3-portal.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
- test/analytics/modeling-on-athena/data-modeliing-athena-stack.test.ts
- test/cdk-lambda-nodejs-mock.ts
- test/control-plane/alb-control-plane-stack.test.ts
- test/control-plane/alb-lambda-portal.test.ts
- test/control-plane/click-stream-api.test.ts
- test/control-plane/cloudfront-control-plane-stack.test.ts
- test/control-plane/cloudfront-s3-portal.test.ts
- test/data-pipeline/data-pipeline-stack.test.ts
- test/ingestion-server/server/ingestion-server-stack.test.ts
- test/ingestion-server/server/ingestion-server-v2-stack.test.ts
- test/ingestion-server/server/ingestion-server-v2.test.ts
- test/ingestion-server/server/ingestion-server.test.ts
- test/jestEnv.js
- test/metrics/metrics-stack.test.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
- test/service-catalog-appregistry/service-catalog-appregistry-stack.test.ts
- test/streaming-ingestion/streaming-ingestion-stack.test.ts
----
Skip all assets build in local test environments:
- **BucketDeployment** asset build
- **NodejsFunction** code build
- **Backend** api docker build
**Local testing time(`pnpm test`): 1070s --> 180s**
> chore: optimize local testing performance

- src/control-plane/backend/lambda/sfn-workflow/index.ts
- test/control-plane/lambda/sfn-workflow.test.ts
> fix: stack create error when pre stack output is null

- src/analytics/private/sqls/redshift/fn-parse-utm-from-url.sql
----
- Data API limit a single sql less than 100K.
- remove all domains that do not end with `.com`
- only keep first level domains, remove domains like 'xxx.xxxx.com'
- the sql file is 63K now
> fix: limit sql to less than 100K

- src/control-plane/backend/lambda/api/service/quicksight/templates/attribution-table-chart.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/event-bar-chart-multiple.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/event-bar-chart.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/event-line-chart-multiple.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/event-line-chart.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/event-pivot-table-chart-multiple.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/event-pivot-table-chart.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/event-table-chart.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-bar-chart-multiple.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-bar-chart.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-funnel-chart.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/path-sankey-chart.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/retention-bar-chart-multiple.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/retention-bar-chart.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/retention-line-chart-multiple.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/retention-line-chart.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/retention-pivot-table-chart-multiple.json
- src/control-plane/backend/lambda/api/service/quicksight/templates/retention-pivot-table-chart.json
----
[mustache HTML-escaped by default](https://www.npmjs.com/package/mustache#variables)
> fix: escaped HTML in dashboard title

- frontend/src/pages/analytics/analytics-utils.ts
- frontend/src/pages/analytics/comps/AttributeGroup.tsx
- frontend/src/ts/utils.ts
- src/control-plane/backend/lambda/api/service/display.ts
- src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
- src/control-plane/backend/lambda/api/test/api/metadata-v3.test.ts
- src/control-plane/backend/lambda/api/test/api/metadata.test.ts
> chore: append is_first_day_event in metadata

- src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
- src/data-pipeline/utils/utils-lambda.ts
- test/data-pipeline/emr-job-submitter.test.ts
----
the function `getRuleConfigDir()` should be invoked in lambda, not in CDK code. 
> fix: wrong traffic source configuration rule s3 path

- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/service/pipeline.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
> chore: check app timezone when upgrade

- src/control-plane/backend/lambda/batch-insert-ddb/index.ts
- test/control-plane/lambda/batch-insert-ddb.test.ts
> chore: use existing physicalId of batch insert lambda to recognize it as an updatable resource

- src/control-plane/backend/lambda/batch-insert-ddb/index.ts
- test/control-plane/lambda/batch-insert-ddb.test.ts
… as an updatable resource (#1119)
----
> chore: use existing physicalId of batch insert lambda to recognize as an updateable resource

- src/data-pipeline/utils/utils-lambda.ts
- test/data-pipeline/data-pipeline-stack.test.ts
> fix: lambda put s3 role permissions

- src/control-plane/backend/lambda/api/service/stack.ts
- src/control-plane/backend/lambda/api/test/api/workflow.test.ts
> fix: retry all stacks when delete failed

- src/analytics/private/metrics-common-workflow.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
> fix: add Refresh materialized views metric

- src/analytics/private/metrics-common-workflow.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
----
add alarm for sql execution
add alarm for sql execution
> chore: add alarm for sql execution

- src/control-plane/backend/lambda/sfn-action/index.ts
- src/control-plane/backend/lambda/sfn-workflow/index.ts
- test/control-plane/lambda/sfn-action.test.ts
> fix: catch exceptions since CFN SDK operations are not idempotent

- src/control-plane/backend/event-bus-construct.ts
- src/control-plane/backend/lambda/api/service/stack.ts
- src/control-plane/backend/lambda/api/store/aws/cloudformation.ts
- src/control-plane/backend/lambda/listen-stack-status/index.ts
- src/control-plane/backend/lambda/listen-stack-status/listen-tools.ts
- src/control-plane/backend/lambda/listen-state-status/index.ts
- src/control-plane/backend/stack-action-state-machine-construct.ts
- test/control-plane/click-stream-api.test.ts
- test/control-plane/lambda/listen-state-status.test.ts
- test/jestEnv.js
> chore: compensation all stacks status when execution is final state

- src/analytics/parameter.ts
- src/common/parameters.ts
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
> chore: delete DataFreshnessInHour for data modeling stack

- src/analytics/private/sqls/redshift/sp-scan-metadata.sql
> fix: long field value causes scanning workflow failure

- src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_country_new_user_sp.sql
- src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_traffic_source_user_sp.sql
- src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition_sp.sql
- src/reporting/private/template-def-spice.json
- src/reporting/private/template-def.json
----
Traffic source should prefix with First User
Session source rename to be Session traffic source
GEO new user count is 0 in some city
Device screen resolution should be width x height
dashboard to change calculation of avg_engagement_time: sum of user engagement time / totoal distinct active user
> fix: dashboard issues polish

- src/data-reporting-quicksight-stack.ts
- src/reporting/parameter.ts
- test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
> fix: add default db param to Reporting stack

- src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/Cache.java
- src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/CacheTest.java
Caused by: java.lang.ClassCastException: class java.util.LinkedHashMap$Entry cannot be cast to class java.util.HashMap$TreeNode (java.util.LinkedHashMap$Entry and java.util.HashMap$TreeNode are in module java.base of loader bootstrap)
----
> fix: ETL cache error when processing huge data

- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
- src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
> chore: add RedshiftDefaultDBParam for reporting stack

- src/common/model.ts
- src/data-pipeline/lambda/emr-job-state-listener/index.ts
- src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/UAEnrichmentV2.java
- src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/Cleaner.java
- src/data-pipeline/utils/metrics.ts
- test/data-pipeline/emr-job-listener.test.ts
> chore: ETL add metrics filtered by appIds, freshness, future, bot

- src/analytics/lambdas/refresh-materialized-views-workflow/check-start-sp-refresh.ts
- test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/check-start-sp-refresh.test.ts
----
set default forceRefresh as true
> chore: set default forceRefresh as true

- src/analytics/lambdas/redshift-data.ts
- test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts
- test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/refresh-basic-view.test.ts
> chore: add redshift retry

- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/service/stack.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow.test.ts
> fix: add reporting stack with action error

- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
> fix: retry when delete failed

- src/analytics/lambdas/scan-metadata-workflow/check-scan-metadata-status.ts
- src/analytics/private/scan-metadata-workflow.ts
- test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/check-scan-metadata-status.test.ts
…data status timeout
----
remove operation of deleting clickstream log to avoid check scan metadata timeout
the clickstream log should be deteted by clear history data workflow
> chore: remove deleting clickstream log in scanning metadata to mitigate timeout

- sonar-project.properties
> chore: exclude build folder of etl-common in sonar scan

- src/data-pipeline/utils/metrics.ts
- test/data-pipeline/data-pipeline-stack.test.ts
> fix: ETL job failed alarm is not triggered

- frontend/src/pages/pipelines/detail/comps/Processing.tsx
- frontend/src/ts/url.ts
> fix: redshift serverless link in GCR

- src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
> chore: keep users state to 10 years in ETL

- src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
----
total file size: 291G, 218,345,393 events
if initialExecutors=10 the job ran 219 mins, then failed, changed to 20 the job completed within 21 minutes(tested twice).
> chore: adjust EMR initialExecutors for large volume data 

- src/ingestion-server/server/parameter.ts
- test/ingestion-server/server/ingestion-server-stack.test.ts
- test/ingestion-server/server/ingestion-server-v2-stack.test.ts
----
refactor pattern to support backslash in authenticationSecretArnParam
> chore: refactor pattern to support backslash in authenticationSecretArnParam

- src/ingestion-server/server/parameter.ts
- test/ingestion-server/server/ingestion-server-stack.test.ts
> chore: support backslash in authenticationSecretArn

- .github/workflows/build.yml
- .github/workflows/dist-scan.yml
- .projen/tasks.json
- .projenrc.js
> ci: specify jest workers for stabilizing the build

- src/analytics/private/sqls/redshift/migrate/sp-migrate-event-to-v2.sql
> fix: app_version is null after migrating old data

- src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ETLRunner.java
> fix: improve ETL performance

- src/analytics/private/load-ods-data-workflow.ts
- test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
----
set timeout longer to handle large ods file number
> chore: set timeout longer to handle large ods file number

- .github/workflows/build.yml
- .projenrc.js
- src/private/function.ts
----
use the workaround suggested in https://github.com/nodejs/node/issues/51555
> chore: mitigate intermitent failure of ci build

- src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
- src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java
> fix: traffic source medium for internal referrer

- src/data-pipeline/etl-common/build.gradle
- src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/ingest/User.java
----
change ETL common to java 11 compatibility, so we can use it in Flink (java11)
> chore: ETL common java 11 compatibility

- src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
- src/control-plane/backend/lambda/api/test/api/reporting.test.ts
> fix: support warmup sql in shared database

- src/analytics/lambdas/clear-expired-events-workflow/check-clear-status.ts
- src/analytics/private/sqls/redshift/migrate/sp-migrate-data-to-v2.sql
- test/analytics/analytics-on-redshift/lambda/clear-expire-events/check-clear-status.test.ts
> fix: use incorrect log table in migration sql

- src/analytics/private/sqls/redshift/sp-merge-session.sql
----
Refactor merge session sql to avoid duplicate records:
1, Just use session_id and user_pseudo_id as the primary key
2, If the record is existing, and session source is "Direct", "" or NULL,  update the record with incoming value. Otherwise not update.
3. Scenarios as below:
- Scenario1: 
old:  "Direct" or Null
new: Not "Direct" and Not Null
result: new value
- Scenario2:
old:  Null
new:   any
result: new value
- Scenario3:
old: "Direct"
new:   Null
result:  "Direct"
- Scenario4:
old:  Not "Direct" and Not Null
new:   "Direct" or Null
result:  old value
-- mingtong added
- Scenario5:
old: "Direct"
new:   Any not Null
result:  new value
(describe how the merge request …
> fix: mitigate the duplicated sessions

- src/data-pipeline/etl-common/build.gradle
- src/data-pipeline/etl-common/gradle.properties
- src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/Cache.java
- src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/UAEnrichHelper.java
- src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/CacheTest.java
- src/data-pipeline/spark-etl/build.gradle
- src/data-pipeline/spark-etl/gradle.properties
> fix: use caffeine cache in ETL

- src/control-plane/backend/lambda/sfn-action/index.ts
- test/control-plane/lambda/sfn-action.test.ts
> chore: use stack parameter previous value

- .projenrc.js
- frontend/package.json
- sonar-project.properties
> chore: specify coverage provider for frontend

- src/base-lib/src/constant/dashboard.ts
> fix: keep user_m_view and item_m_view when upgrade to 1.1.6

- src/control-plane/backend/lambda/sfn-action/index.ts
- test/control-plane/lambda/sfn-action.test.ts
> fix: upgrade pipeline with deleted paramters

- frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx
> fix: disable switch of app streaming without the streaming module

- src/analytics/lambdas/refresh-materialized-views-workflow/refresh-basic-view.ts
- src/analytics/private/refresh-materialized-views-workflow.ts
- test/analytics/analytics-on-redshift/lambda/refresh-materialized-views-workflow/refresh-basic-view.test.ts
> chore: use refresh start time to refresh base view

- src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/TransformerV3.java
- src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/BaseThirdPartyTransformer.java
- src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/TransformerV3Test.java
> fix: ETL job failure when input dataset is empty

- src/reporting/lambda/custom-resource/quicksight/index.ts
- test/reporting/quicksight/lambda/quicksight-resource.test.ts
> fix: realtime dashboard using wrong template definition

- src/ingestion-server/custom-resource/update-alb-rules/index.ts
- test/ingestion-server/custom-resource/update-alb-rules.test.ts
----
compatible from v1 upgrading to v2
> fix: backward compatible for alb updating custom resource

- frontend/src/pages/analytics/segments/UserSegmentDetails.tsx
----
Add refresh button on segment detail page
> chore: add refresh button on segment detail page

- src/streaming-ingestion/parameter.ts
> chore: reduce Flink application default parallelism to 1

- frontend/public/locales/en-US/analytics.json
- frontend/public/locales/zh-CN/analytics.json
- frontend/src/index.scss
- frontend/src/pages/analytics/realtime/AnalyticsRealtime.tsx
> chore: auto refresh realtime dashboard

- src/data-pipeline/spark-etl/build.gradle
----
- tested on Instance with 64 vCPU EC2 instance, the build succeed in 8 mins.
- tested on Instance with 16 vCPU EC2 instance, the build succeed in 10 mins.
> tests: limit max parallel in ETL test

- frontend/public/locales/en-US/analytics.json
- frontend/public/locales/en-US/common.json
- frontend/public/locales/zh-CN/analytics.json
- frontend/public/locales/zh-CN/common.json
- frontend/src/AppRouter.tsx
- frontend/src/apis/segments.ts
- frontend/src/pages/analytics/segments/AddUserSegment.tsx
- frontend/src/pages/analytics/segments/ImportUserSegment.tsx
- frontend/src/pages/analytics/segments/UserSegmentDetails.tsx
- frontend/src/pages/analytics/segments/UserSegments.tsx
- frontend/src/ts/const.ts
- src/base-lib/src/model/segment.ts
- src/control-plane/backend/lambda/api/router/segment.ts
- src/control-plane/backend/lambda/api/service/segments/segment.ts
- src/control-plane/backend/lambda/api/test/api/segments/segments.test.ts
----
Support user imported segment by adding a new page and import api. User can import segment user to database manually later. For simplicity, import segment only supports CREATE and DELETE operations.
> feat: import segment

- src/ingestion-server/kinesis-data-stream/private/kinesis.ts
- test/ingestion-server/server/ingestion-server-stack.test.ts
- test/ingestion-server/server/ingestion-server-v2-stack.test.ts
----
clean KDS after removing ingestion module
> chore: clean KDS after removing ingestion module

- src/metrics-stack.ts
- test/metrics/metrics-stack.test.ts
----
remove custom kms after stack is deleted
Deploy metric stack and delete successfully
> chore: remove custom kms after stack is deleted

- frontend/public/locales/en-US/common.json
- frontend/src/pages/analytics/realtime/AnalyticsRealtime.tsx
- frontend/src/pages/pipelines/detail/comps/Ingestion.tsx
- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/service/application.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/store/aws/flink.ts
- src/control-plane/backend/lambda/api/test/api/application.test.ts
> chore: start/stop flink app after enabling/disabling streaming report in analysis studio  

- frontend/src/pages/analytics/segments/UserSegmentDetails.tsx
- frontend/src/pages/analytics/segments/components/SegmentEditor.tsx
- src/analytics/lambdas/user-segments-workflow/state-machine-status.ts
- src/analytics/private/segments/user-segments-workflow.ts
- test/analytics/analytics-on-redshift/lambda/user-segments-workflow/state-machine-status.test.ts
- test/analytics/analytics-on-redshift/workflow/user-segments-sfn.json
- test/analytics/analytics-on-redshift/workflow/user-segments-sfn.test.ts
----
1. Fix segment jobs got stuck when multiple jobs were submitted
2. Fix segment job is not showing up in the job list table in segment detail page
3. Fix segment refresh schedule cron is incorrect for daily refresh
4. Display segment name instead of segment id in the breadcrums
> fix: segment jobs got stuck when multiple jobs were submitted

- frontend/public/locales/en-US/analytics.json
- frontend/public/locales/zh-CN/analytics.json
- frontend/src/apis/analytics.ts
- frontend/src/index.scss
- frontend/src/pages/analytics/realtime/AnalyticsRealtime.tsx
- src/control-plane/backend/lambda/api/middle-ware/auth-role.ts
- src/control-plane/backend/lambda/api/router/project.ts
- src/control-plane/backend/lambda/api/router/reporting.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/store/aws/flink.ts
- src/control-plane/backend/lambda/api/test/api/realtime.test.ts
----
1. check flink status before switch changed
2. move realtime api router to reporting and add auth
3. add cost tips
> chore: polish realtime switcher

- src/ingestion-server/common-resources/ingestion-common-resources.ts
- src/ingestion-server/server-v2/private/ecs-fargate-service.ts
- test/ingestion-server/server/ingestion-server-v2.test.ts
- test/ingestion-server/server/ingestion-server.test.ts
----
fix scale time to minute for fargate, ingestion v2 output key
> fix: scale time of ecs fargate service and ingestion v2 output key

- frontend/public/locales/en-US/pipeline.json
- frontend/public/locales/zh-CN/pipeline.json
- frontend/src/pages/pipelines/create/steps/Reporting.tsx
- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/service/project.ts
- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow.test.ts
> fix: create built-in user base on Quicksight auth type

- src/data-pipeline/spark-etl/build.gradle
- src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/BaseSparkTest.java
> tests: make spark ETL tests more stable when running in parallel

- docs/en/plan-deployment/cost.md
- docs/zh/plan-deployment/cost.md
----
update cost document for fargate
> chore: add ECS Fargate type in cost

- src/analytics/private/sqls/redshift/sp-clear-expired-data.sql
----
clear expired streaming data, tested when mv_tbl__ods_events_streaming_mv__0 is existing and not
> chore: clear expired streaming data

- frontend/public/locales/en-US/pipeline.json
- frontend/public/locales/en-US/user.json
- frontend/public/locales/zh-CN/pipeline.json
- frontend/public/locales/zh-CN/user.json
- frontend/src/pages/pipelines/create/CreatePipeline.tsx
- frontend/src/pages/pipelines/create/steps/ConfigIngestion.tsx
- frontend/src/pages/projects/Projects.tsx
- frontend/src/pages/user/UserHeader.tsx
- frontend/src/pages/user/UserList.tsx
- frontend/src/pages/user/UserTableHeader.tsx
- frontend/src/types/pipeline.d.ts
- frontend/test/service-available.test.tsx
- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/model/stacks.ts
- src/control-plane/backend/lambda/api/service/application.ts
- src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
- src/control-plane/backend/lambda/api/test/api/workflow.test.ts
- src/streaming-ingestion/parameter.ts
- test/streaming-ingestion/streaming-ingestion-stack.test.ts
> chore: set the default RetentionHours of real-time events to 24 hours

- frontend/public/locales/en-US/analytics.json
- frontend/public/locales/zh-CN/analytics.json
- frontend/src/pages/analytics/analytics-utils.ts
- frontend/src/pages/analytics/segments/ImportUserSegment.tsx
- frontend/src/pages/analytics/segments/UserSegmentDetails.tsx
- frontend/src/pages/analytics/segments/UserSegments.tsx
- frontend/src/pages/analytics/segments/components/SegmentEditor.tsx
- src/base-lib/src/common/utils.ts
- src/base-lib/test/utils.test.ts
----
1. Show readable string for Refresh Schedule in segment list page
2. Hide Expiration settings when Refresh method is Manual
3. Move Import button out of Actions dropdown
4. Add guide for import page, the link is a placeholder, will update after segments doc is updated
5. Some other UI polish and wording changes
> chore: segments UI polish

- deployment/build-s3-dist.sh
- deployment/cdk-solution-helper/index.js
> chore: change repo name to clickstream-proxy and clickstream-worker

- src/common/model.ts
- src/control-plane/backend/lambda/api/common/utils.ts
- src/control-plane/backend/lambda/api/config/dictionary.json
- src/control-plane/backend/lambda/api/model/pipeline.ts
- src/control-plane/backend/lambda/api/service/reporting.ts
- src/control-plane/backend/lambda/api/service/stack-excution.ts
- src/control-plane/backend/lambda/api/service/stack.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
- src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
- src/control-plane/backend/lambda/api/test/api/workflow.test.ts
> chore: use fixed stack name for ingestion server when using v2 template

- src/kafka-s3-connector-stack.ts
- test/ingestion-server/kafka-s3-connector/kafka-s3-connector-stack.test.ts
----
change kafka connector plugin endpoint according below document
https://docs.confluent.io/platform/current/connect/confluent-hub/index.html
> fix: change the download url of kafka s3 connector plugin

- src/control-plane/backend/lambda/api/store/aws/quicksight.ts
- src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
> fix: dashboard create failed when reporting user arn is empty

- src/analytics/private/sqls/redshift/event-v2.sql
- src/control-plane/backend/lambda/api/config/dictionary.json
----
Some preset event attribute description contains html <a> tag, which violates the XSS rule and prevents new segment from being created. Update event attribute description to remove html <a> tag.
Note that the UI already has input check to prevent user from adding description with html tags.
> chore: update event attribute description to remove html tag

- src/ingestion-server/server-v2/private/ecs-ec2-cluster.ts
> chore: update base OS of ingestion servers to Amazon Linux 2023

- src/ingestion-server/server-v2/private/ecs-ec2-cluster.ts
- src/ingestion-server/server/ingestion-server.ts
- src/ingestion-server/server/private/cfn-nag.ts
- src/ingestion-server/server/private/ecs-cluster.ts
- test/ingestion-server/server/TestTask-v2.ts
- test/ingestion-server/server/ingestion-server-v2.test.ts
- test/ingestion-server/server/ingestion-server.test.ts
----
use launch template to replace launch configuration
> chore: use launch template to replace launch configuration

- src/control-plane/backend/lambda/api/service/stack.ts
- src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
- src/control-plane/backend/lambda/api/test/api/workflow.test.ts
> fix: retry failed when stackTemplateVersion is null

- src/analytics/private/sqls/redshift/sp-scan-metadata.sql
----
handle custom_parameters more than 65535 case
> fix: handle the large size of custom parameters exceeding maximum VARCHAR

- src/control-plane/backend/stack-action-state-machine-construct.ts
- test/control-plane/click-stream-api.test.ts
> fix: add missing policy action for assuming role update
