buildspec.yml
deployment/build-s3-dist.sh

chore: move check SOLUTION_VERSION before running unit tests

---

README.md

chore: update doc link in readme

---

src/control-plane/backend/lambda/api/common/stack-params-valid.ts
src/control-plane/backend/lambda/api/common/types.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/service/stack.ts
src/control-plane/backend/lambda/api/test/api/workflow.test.ts
src/control-plane/backend/lambda/sfn-action/index.ts

fix: enable rollback when update & upgrade pipeline with tags

---

src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/control-plane/backend/lambda/api/test/api/env.test.ts

fix: create function for get identity region from error message

---

.github/ISSUE_TEMPLATE/feature_request.md

chore: update feature request template

---

frontend/public/locales/en/common.json
frontend/public/locales/zh/pipeline.json
frontend/public/locales/zh/plugin.json

fix: typos in web console UI

---

.projen/deps.json
.projenrc.js
package.json
src/control-plane/backend/lambda/api/.projen/deps.json
src/control-plane/backend/lambda/api/common/sql-builder.ts
src/control-plane/backend/lambda/api/package.json
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
src/control-plane/backend/lambda/api/yarn.lock
test/control-plane/sql-builder.test.ts
yarn.lock

feat: add sql builder for funnel chart

---

frontend/src/ts/guideConst.ts

chore: set 'compression' as default true for SDK configurations

---

frontend/public/locales/en/application.json
frontend/public/locales/en/plugin.json

----
Fix some typo
Plase ===> Please

fix: fix some tpyo

---

frontend/src/components/layouts/Header.tsx

chore: delete bad url in top navigation

---

frontend/src/components/layouts/Header.tsx

fix: delete broken and duplicated links in top navigation

---

src/control-plane/backend/lambda/sfn-action/index.ts
test/control-plane/lambda/sfn-action.test.ts

fix: retry the failed stacks

---

.projen/deps.json
.projenrc.js
NOTICE.txt
package.json
yarn.lock

chore: remove unused readline

---

docs/en/getting-started/2.config-pipeline.md
docs/zh/getting-started/2.config-pipeline.md

----
Add S3 and VPC security related document

docs: add tips for S3 and VPC security best practices

---

docs/en/pipeline-mgmt/ingestion/index.md
docs/zh/pipeline-mgmt/ingestion/index.md

----
Add throttling statement into document

docs: add throttling statement for ingestion

---

.github/workflows/ghpage.yml

chore: build the docs when only the docs source are changed

---

src/control-plane/backend/stack-action-state-machine-construct.ts
test/control-plane/click-stream-api.test.ts

fix: add UpdateRoleDescription permission for upgrade

---

frontend/src/components/eventselect/DropDownContainer.tsx
frontend/src/components/eventselect/EventItem.tsx
frontend/src/components/eventselect/comps/ItemsList.tsx
frontend/src/index.scss
frontend/src/pages/analytics/event/AnalyticsEvent.tsx

chore: support filter in analytics component

---

src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts

chore: ETL reduce TS function Cognitive Complexity

---

src/metrics/custom-resource/put-dashboard/index.ts

chore: Metrics reduce TS function Cognitive Complexity

---

src/data-pipeline/spark-etl/gradle/config/checkstyle/sun_checks.xml
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/Cleaner.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ContextUtil.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/DataProcessor.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ETLRunner.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ETLRunnerConfig.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/IPEnrichment.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/KvConverter.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/Transformer.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/UAEnrichment.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/UserPropertiesConverter.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/exception/ExecuteTransformerException.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/exception/ExtractDataException.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/BaseSparkTest.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/CleanerTest.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/ContextUtilTest.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/DataProcessorTest.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/ETLRunnerTest.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/EventParamsConverterTest.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/ExceptionTest.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/IPEnrichmentTest.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/TransformerTest.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/UAEnrichmentTest.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/UserPropertiesConverterTest.java

chore: improve java code quality in spark ETL

---

src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ContextUtil.java

chore: ETL change debug print to log.error

---

frontend/public/locales/en/application.json
frontend/public/locales/zh/application.json
frontend/src/pages/application/detail/ApplicationDetail.tsx
frontend/src/pages/application/detail/comp/ConfigAndroidSDK.tsx
frontend/src/pages/application/detail/comp/ConfigIOSSDK.tsx
frontend/src/pages/application/detail/comp/ConfigWebSDK.tsx
frontend/src/ts/guideConst.ts

chore: ui add web sdk guide

---

src/ingestion-server/custom-resource/update-alb-rules/index.ts
src/ingestion-server/kafka-s3-connector/custom-resource/kafka-s3-sink-connector/index.ts
src/ingestion-server/server/condition.ts
src/ingestion-server/server/ingestion-server.ts
src/ingestion-server/server/parameter.ts
src/kafka-s3-connector-stack.ts

----
Resolve sonarqube scan issue of ingestion server
Resolve scan issue of ingestion server, and did below test cases:
1. Deploy MSK sink
2. Deploy S3 sink
3. Update appIds and endpoint path

chore: polish code of ingestion server

---

frontend/src/pages/application/create/comp/RegisterApp.tsx

fix: add web SDK guide in create app page

---

src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ETLRunner.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/ETLRunnerTest.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/SimpleEnrich.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/SimpleTransformer.java

chore: add postTransform hook for transformer plugin

---

src/data-pipeline-stack.ts
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/KvConverter.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/Transformer.java
src/main.ts
src/metrics/custom-resource/get-interval/index.ts
src/metrics/custom-resource/put-dashboard/index.ts

chore: polish code in ETL pipeline

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

feat: support count on user_id 

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

chore: cache connection to improve performance of create Redshfit view and QuickSight resources

---

src/control-plane/backend/lambda/api/router/reporting.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

feat: warm up reporting service

---

docs/en/sdk-manual/android.md
docs/zh/sdk-manual/android.md

----
1. add the screen view definition
2. update the definition of session
3. update the definition of user engagement
4. update the example event for record an event
5. add the data type for each attribute
6. add reference link
7. adjust the content structure
8. update the error code
9. fix typo

docs: update android sdk

---

frontend/src/apis/analytics.ts
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
src/control-plane/backend/lambda/api/service/reporting.ts

feat: warm up when access explore page

---

docs/en/sdk-manual/swift.md
docs/mkdocs.base.yml
docs/zh/sdk-manual/swift.md

----
1. add the screen view definition
2. update the definition of session
3. update the definition of user engagement
4. update the example event for record an event
5. add the data type for each attribute
6. add reference link
7. adjust the content structure
8. update the error code
9. fix typo

docs: update swift sdk

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting-utils.test.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

feat: create QuickSight dataset using custom sql

---

docs/en/sdk-manual/android.md
docs/zh/sdk-manual/android.md

----
1. fix the format of android code

docs: format Android code snippet

---

frontend/package.json
frontend/src/components/eventselect/AnalyticsType.ts
frontend/src/components/eventselect/EventItem.tsx
frontend/src/components/eventselect/EventSelect.tsx
frontend/src/components/eventselect/RetentionItem.tsx
frontend/src/components/eventselect/RetentionSelect.tsx
frontend/src/index.scss
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx
frontend/yarn.lock

chore: add retention event select component

---

frontend/public/locales/en/analytics.json
frontend/public/locales/zh/analytics.json
frontend/src/components/eventselect/AnalyticsType.ts
frontend/src/components/eventselect/ConditionItem.tsx
frontend/src/pages/analytics/analytics-utils.ts

chore: select component support select&input value enums

---

frontend/src/App.tsx
frontend/src/components/common/RoleRoute.tsx
frontend/src/components/layouts/AnalyticsHeader.tsx
frontend/src/components/layouts/AnalyticsLayout.tsx
frontend/src/components/layouts/AnalyticsNavigation.tsx
frontend/src/components/layouts/CommonLayout.tsx
frontend/src/index.scss
frontend/src/pages/analytics/dashboard/AnalyticsDashboard.tsx
frontend/src/ts/const.ts

chore: add analytics layout

---

src/data-pipeline/utils/custom-resource.ts
test/data-pipeline/data-pipeline-stack.test.ts

----
close https://github.com/awslabs/clickstream-analytics-on-aws/issues/225

fix: typo secourityGroupId -> securityGroupId

---

src/control-plane/backend/click-stream-api.ts
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/middle-ware/auth-role.ts
src/control-plane/backend/lambda/api/service/user.ts
src/control-plane/backend/lambda/api/test/api/auth.test.ts
src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
test/control-plane/click-stream-api.test.ts

fix: get user role error from token group

---

frontend/src/components/common/RoleRoute.tsx

fix: access denied page layout

---

docs/en/sdk-manual/android.md
docs/zh/sdk-manual/android.md

----
1. update the description of android SDK version

docs: update android SDK version

---

src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/TransformerV2.java
src/data-pipeline/utils/custom-resource.ts
test/data-pipeline/data-pipeline-stack.test.ts

----
relate to https://github.com/awslabs/clickstream-analytics-on-aws/issues/226

fix: failed to create emr serverless application when no existing emr-serverless service link role

---

src/common/constant.ts
src/control-plane/auth/authorizer.ts
src/control-plane/backend/lambda/api/common/request-valid.ts
src/control-plane/backend/lambda/api/common/stack-params-valid.ts
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/middle-ware/auth-oidc.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/model/stacks.ts
src/control-plane/backend/lambda/api/router/reporting.ts
src/control-plane/backend/lambda/api/router/user.ts
src/control-plane/backend/lambda/api/service/application.ts
src/control-plane/backend/lambda/api/service/display.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/service/stack.ts
src/control-plane/backend/lambda/api/service/user.ts
src/control-plane/backend/lambda/api/store/aws/iam.ts
src/control-plane/backend/lambda/api/store/aws/kafka.ts
src/control-plane/backend/lambda/api/test/api/utils.test.ts
src/control-plane/backend/lambda/sfn-workflow/index.ts
src/reporting/parameter.ts

chore: polish backend api code

---

src/control-plane/backend/lambda/sfn-workflow/index.ts
test/control-plane/lambda/sfn-workflow.test.ts

fix: workflow init parameters error

---

frontend/src/components/eventselect/AnalyticsType.ts
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/ts/explore-types.ts
frontend/src/types/analytics.d.ts
src/control-plane/backend/lambda/api/common/explore-types.ts
src/control-plane/backend/lambda/api/model/metadata.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

fix: add condition category to parameters

---

docs/mkdocs.base.yml
docs/overrides/partials/integrations/analytics/custom.html

docs: add analytics config

---

frontend/src/components/layouts/AnalyticsNavigation.tsx

chore: delete realtime from nav

---

frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx

fix: filter select option init empty

---

docs/en/pipeline-mgmt/data-processing/data-schema.md
docs/zh/pipeline-mgmt/data-processing/data-schema.md

docs: correct field name

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

----
fix a bug when  create funnel type chart

fix: error when create funnel type chart

---

src/control-plane/backend/insert-admin-user.ts

chore: update admin user customer resource physicalResourceId

---

src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

fix: QuickSight throttling exception when delete temporary resources

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

----
1. check check exploratory analysis api parameters and return 400 if not pass the check
2. fix #287 

chore: check exploratory analysis api parameters

---

frontend/src/pages/analytics/analytics-utils.ts
frontend/src/types/analytics.d.ts

fix: incorrect compute method name

---

frontend/src/ts/utils.ts

chore: optimize regex code

---

frontend/src/ts/utils.ts

chore: optimize new regex code

---

src/analytics/lambdas/custom-resource/create-schemas.ts

chore: reduce code cognitive complexity in create-schemas

---

frontend/src/ts/test/utils.test.ts
frontend/src/ts/utils.ts

fix: generateStr method generate same character #304

---

.projenrc.js
frontend/package.json
frontend/src/index.scss
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/data-management/AnalyticsDataManagement.tsx
frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/metadata/event-parameters/MetadataParametersTable.tsx
frontend/src/pages/analytics/metadata/events/MetadataEventsTable.tsx
frontend/src/pages/analytics/metadata/user-attributes/MetadataUserAttributesTable.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/pages/common/Tags.tsx
frontend/src/ts/utils.ts
frontend/yarn.lock
package.json
src/control-plane/backend/lambda/api/package.json
src/control-plane/backend/lambda/api/yarn.lock
yarn.lock

fix: frontend analytics filter issues reduce cognitive complexity

---

frontend/src/ts/const.ts

fix: language switcher is not changed after switching to another language

---

frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx

fix: correct view application detail button link

---

frontend/src/components/eventselect/DropDownContainer.tsx
frontend/src/components/eventselect/comps/AttributePreview.tsx
frontend/src/components/eventselect/comps/EventPreview.tsx
frontend/src/index.scss

chore: rename classname

---

frontend/src/pages/pipelines/create/CreatePipeline.tsx
frontend/src/pages/pipelines/create/steps/ConfigIngestion.tsx
frontend/src/pages/pipelines/create/steps/DataProcessing.tsx
frontend/src/pages/pipelines/create/steps/buffer/BufferMSK.tsx
frontend/src/pages/pipelines/detail/comps/Ingestion.tsx
frontend/src/pages/plugins/comps/PluginTable.tsx
frontend/src/ts/utils.ts

chore: reduce frontend cognitive complexity for pipeline management

---

src/control-plane/backend/lambda/api/common/utils.ts

----
handle the case that without data for last day
handle the case that without data for last day

fix: handle the case that without data for last day

---

frontend/src/pages/pipelines/detail/comps/Processing.tsx
frontend/src/ts/utils.ts

chore: reduce frontend cognitive complexity for utils and processing

---

frontend/src/pages/analytics/analytics-utils.ts

fix: pass wrong event name

---

src/data-pipeline/lambda/emr-job-state-listener/index.ts
src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
src/data-pipeline/lambda/emr-serverless-app/index.ts
src/data-pipeline/lambda/partition-syncer/index.ts

chore: polish code in data pipeline

---

src/control-plane/backend/config/dictionary.json

chore: update metadata built-in list

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/components/eventselect/AnalyticsType.ts
frontend/src/components/eventselect/EventItem.tsx
frontend/src/components/eventselect/EventSelect.tsx
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/comps/ExploreDateRangePicker.tsx
frontend/src/pages/analytics/comps/StartNodeSelect.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx
frontend/src/types/analytics.d.ts
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/service/metadata.ts
src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
src/control-plane/backend/lambda/api/test/api/metadata.test.ts
src/main.ts

----
1. Date range component: date range don't change with time granularity
2. Path nodes select add start node
3. Fix no group parameter in api request
4. Fix event parameter(Public/Private) display
5. Fix backend api: the issue of losing some parameters

fix: path explore issues

---

frontend/src/pages/analytics/analytics-utils.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

fix: explore error with group condition 

---

frontend/src/pages/pipelines/create/CreatePipeline.tsx

chore: reduce create pipeline cognitive complexity

---

src/analytics/private/sql-def.ts
src/analytics/private/sqls/redshift/sp-migrate-ods-events-1.0-to-1.1.sql
test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts

chore: sp migrate ods_events from 1.0 to 1.1

---

src/analytics/lambdas/custom-resource/create-schemas.ts
src/analytics/private/sql-def.ts
src/analytics/private/sqls/redshift/grant-permissions-to-bi-user-1.sql
src/analytics/private/sqls/redshift/grant-permissions-to-bi-user-2.sql
test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts

tests: polish test case create-schema

---

src/control-plane/backend/lambda/api/common/dynamodb-client.ts
src/control-plane/backend/lambda/api/model/stacks.ts
src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
src/control-plane/backend/lambda/api/test/api/store.test.ts
src/control-plane/backend/lambda/batch-insert-ddb/index.ts

fix: ddb marshall options

---

buildspec.yml

for running build in different codebuild runtime versions
----

chore: update node to latest in codebuild script

---

.viperlightignore
CHANGELOG.md

chore: update changelog

---

.github/dependabot.yml

chore: enable github-actions version updates

---

frontend/src/pages/analytics/comps/SelectDashboardModal.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx
src/common/constant.ts
src/control-plane/backend/lambda/api/common/stack-params-valid.ts
src/control-plane/backend/lambda/api/service/project.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

fix: save visual to dashboard and analysis

---

frontend/src/pages/analytics/comps/AttributeGroup.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-bar-chart-multiple.json
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
src/reporting/lambda/custom-resource/quicksight/index.ts

----
1.fix bug of missing global condition
2.compute retention by week/month

fix: missing global condition

---

frontend/src/components/pipeline/PipelineStatus.tsx

chore: remove unused assignments

---

CHANGELOG.md

chore: merge changelog from 1.0.x branch

---

.github/workflows/build-sub-projects.yml
.github/workflows/build.yml
.github/workflows/dist-scan.yml
.github/workflows/pull-request-lint.yml
.github/workflows/source-scan.yml
.github/workflows/upgrade.yml
.projenrc.js

chore: bump github-actions versions

---

frontend/src/pages/analytics/metadata/event-parameters/MetadataParameterSplitPanel.tsx
frontend/src/pages/analytics/metadata/event-parameters/MetadataParametersTable.tsx
frontend/src/pages/analytics/metadata/table/MetadataDictionaryTable.tsx
frontend/src/pages/analytics/metadata/user-attributes/MetadataUserAttributeSplitPanel.tsx
frontend/src/pages/analytics/metadata/user-attributes/MetadataUserAttributesTable.tsx
src/analytics/private/sqls/redshift/sp-scan-metadata.sql
src/control-plane/backend/config/dictionary.json
src/control-plane/backend/lambda/api/model/metadata.ts
src/control-plane/backend/lambda/api/service/display.ts
src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
src/control-plane/backend/lambda/api/test/api/metadata.test.ts

----
Refactor to add category into id and add more geo properties.
Refactor to add category into id and add more geo properties.

chore: add category into id and add more geo properties

---

frontend/config/webpack.config.js
src/alb-control-plane-stack.ts
src/control-plane/frontend/Dockerfile

chore: Increase frontend build bundle size

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

fix: support same event in event path analysis

---

frontend/src/i18n.ts

fix: i18n resources duplicate loaded

---

frontend/public/locales/en-US/common.json
frontend/public/locales/zh-CN/common.json
frontend/src/App.tsx
frontend/src/AppRouter.tsx
frontend/src/AppSignInPage.tsx
frontend/src/components/common/RoleRoute.tsx
frontend/src/components/layouts/Header.tsx
frontend/src/components/layouts/Navigation.tsx
frontend/src/context/UserContext.ts
frontend/src/pages/error-page/ReSignIn.tsx
frontend/src/ts/const.ts
frontend/src/ts/init.ts
frontend/src/ts/utils.ts

fix #57 
resolve loading all page when user navigating.
resolve page refreshing after user token expired.
----

chore: Improve user experience in the web ui

---

frontend/src/components/pipeline/PipelineStatus.tsx

fix: use pending state for stacks when creating/updating the pipeline

---

frontend/src/components/common/ExtendIcon.tsx
frontend/src/components/common/title/SectionTitle.tsx
frontend/src/components/layouts/AnalyticsNavigation.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx

chore: ui icons and funnel group condition

---

frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/comps/AttributeGroup.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx

----
1. default explore event model
2. group by private parameters 

chore: group by private parameters 

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/reporting/lambda/custom-resource/quicksight/index.ts
src/reporting/private/dashboard.ts
src/reporting/private/iam.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
test/reporting/quicksight/lambda/quicksight-resource.test.ts

fix: change the principal of reporting not working

---

src/analytics/private/sqls/redshift/sp-scan-metadata.sql

----
Set the max lenght of property value as 255
Set the max lenght of property value as 255

chore: set the max length of property value as 255

---

.github/workflows/ghpage.yml
docs/en/deployment/with-cognito.md
docs/en/deployment/with-oidc.md
docs/images/favicon.ico
docs/index.html
docs/mkdocs.base.yml
docs/zh/deployment/with-cognito.md
docs/zh/deployment/with-oidc.md

chore: publish docs with versioning

---

src/control-plane/backend/lambda/api/service/application.ts
src/control-plane/backend/lambda/api/test/api/application.test.ts

fix: miss app create time

---

frontend/src/components/pipeline/PipelineStatus.tsx
frontend/src/pages/pipelines/comps/BasicInfo.tsx
frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx

fix: auto reload pipeline when status is active

---

.github/workflows/build-sub-projects.yml
.github/workflows/build.yml
.github/workflows/dist-scan.yml
.github/workflows/ghpage.yml
.projenrc.js
docs/en/deployment/with-cognito.md
docs/en/deployment/with-oidc.md
docs/images/favicon.ico
docs/mkdocs.base.yml
docs/overrides/partials/integrations/analytics/custom.html
docs/zh/deployment/with-cognito.md
docs/zh/deployment/with-oidc.md

chore: publish versioning 1.0.x doc

---

frontend/src/pages/pipelines/detail/comps/Reporting.tsx

chore: update reporting dashboard link

---

src/control-plane/backend/lambda/api/service/project.ts
src/control-plane/backend/lambda/api/store/click-stream-store.ts
src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts

fix: dashboard list filter by project and app id

---

frontend/src/index.scss
frontend/src/pages/analytics/metadata/event-parameters/MetadataParametersTable.tsx
frontend/src/pages/common/LabelTag.tsx

chore: add parameter type style

---

frontend/src/pages/analytics/comps/ExploreDateRangePicker.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx

fix: disable selection when chart is loading

---

src/common/constant.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/data-reporting-quicksight-stack.ts
src/reporting/lambda/custom-resource/quicksight/index.ts
src/reporting/parameter.ts
src/reporting/private/dashboard.ts
src/reporting/quicksight-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
test/reporting/quicksight/lambda/quicksight-resource.test.ts

chore: change builtin dashboard owner

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/reporting/lambda/custom-resource/quicksight/index.ts
src/reporting/private/dashboard.ts
src/reporting/quicksight-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
test/reporting/quicksight/lambda/quicksight-resource.test.ts

----
update date set update logic, remove unused data set and create new one if necessary

fix: dataset update fail when upgrade pipeline.

---

frontend/public/locales/en-US/pipeline.json
frontend/public/locales/zh-CN/pipeline.json
frontend/src/index.scss
frontend/src/pages/pipelines/create/CreatePipeline.tsx
frontend/src/pages/pipelines/create/steps/DataProcessing.tsx
frontend/src/pages/plugins/comps/PluginTable.tsx
frontend/test/msk-redshift.test.tsx
frontend/test/service-available.test.tsx
frontend/test/update-pipeline.test.tsx

fix: add transform plugin validation when using third-party SDK

---

src/control-plane/backend/lambda/api/common/constants.ts
src/control-plane/backend/lambda/api/common/stack-params-valid.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts

fix: vpce is not a service endpoint required for our solution

---

src/analytics/private/sqls/redshift/sp-scan-metadata.sql

----
1. Add operation to limit user metadata record numbers
2. Use user_m_view to replace user table.

fix: limit user metadata number and use user view

---

src/control-plane/backend/config/dictionary.json

chore: add new preset parameter

---

frontend/src/AppRouter.tsx

fix: redirect incorrect when user login with different role

---

.github/workflows/ghpage.yml

chore: don't add alias in title for released version

---

.github/workflows/ghpage.yml

chore: update title of docs

---

src/control-plane/backend/lambda/api/router/reporting.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

----
1. api limit event condition as same as frontend
2. api body check XSS 

chore: improve explorative api validation

---

frontend/src/pages/analytics/metadata/user-attributes/MetadataUserAttributesTable.tsx

chore: user attribute table filter properties

---

frontend/src/ts/init.ts

chore: update warm pool default value to 0

---

examples/standalone-data-generator/configure.py
examples/standalone-data-generator/create_event.py
examples/standalone-data-generator/send_event.py
examples/standalone-data-generator/util/util.py

----
1. remove multiprocessing and update configure

chore: remove multiprocessing and update configuration in example data generator

---

frontend/src/pages/pipelines/create/steps/ConfigIngestion.tsx
src/control-plane/backend/lambda/api/model/stacks.ts

- Custom domain
- Global Accelerator
- ALB access log
- Authentication
----

chore: more ingestion configuration can be updated in existing pipeline 

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx
frontend/src/types/analytics.d.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

fix: group condition should only apply to the first event

---

frontend/src/components/common/ExtendIcon.tsx
frontend/src/components/eventselect/ConditionItem.tsx
frontend/src/components/eventselect/RetentionItem.tsx
frontend/src/pages/analytics/comps/ExploreEmbedFrame.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/pages/pipelines/create/CreatePipeline.tsx
frontend/src/pages/pipelines/create/steps/buffer/BufferMSK.tsx
src/control-plane/backend/lambda/api/common/stack-params-valid.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/model/stacks.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts
src/control-plane/backend/lambda/api/test/api/store.test.ts
src/control-plane/backend/lambda/api/test/api/workflow-mock.ts

----
1. display MSK refresh button
2. enforce at least 2 for the maximum for ingestion server
3. filter icon in Retention analysis
4. embed chart placehoder & increase create dashboard wait time to 10s
5. funnel default chart type is bar
6. delete path explore platform and fix node type data
7. auto receive value when input focus is removed from the input

chore: ux improvements

---

src/common/constant.ts
src/control-plane/backend/lambda/api/service/project.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
src/control-plane/backend/lambda/api/test/api/project.test.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

fix: delete analysis while delete dashboard

---

frontend/src/apis/analytics.ts
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
frontend/src/types/analytics.d.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

fix: warmup response 4xx for invalidated inputs

---

src/control-plane/backend/lambda/api/service/user.ts
src/control-plane/backend/lambda/api/test/api/auth.test.ts
src/control-plane/backend/lambda/api/test/api/user.test.ts

fix: return noIdentity role for empty user id

---

frontend/src/pages/pipelines/create/CreatePipeline.tsx

fix: using wrong sdk configuration when switching sdk

---

src/control-plane/backend/config/dictionary.json
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
src/control-plane/backend/lambda/api/test/api/plugin.test.ts
src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
src/control-plane/backend/lambda/api/test/api/workflow.test.ts

fix: wrong class name of GTMServerDataTransformer

---

examples/standalone-data-generator/application/shopping/Products.py
examples/standalone-data-generator/application/shopping/ScreenEvent.py
examples/standalone-data-generator/application/shopping/ShoppingEventType.py
examples/standalone-data-generator/application/shopping/ShoppingScreen.py
examples/standalone-data-generator/enums.py

----
1. support live events in example data generator

chore: add live events in example data generator

---

src/control-plane/backend/click-stream-api.ts
src/control-plane/backend/lambda/api/common/constants.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/service/pipeline.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
test/jestEnv.js

fix: add environment variable for solution version

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts

chore: polish code backend & emr lambda

---

src/analytics/private/sqls/redshift/sp-migrate-ods-events-1.0-to-1.1.sql
src/cloudfront-control-plane-stack.ts
src/control-plane/cloudfront-s3-portal.ts

fix: migration sql error

---

src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
test/data-pipeline/emr-job-submitter.test.ts

fix: wrong time range when dates cross days

---

src/analytics/private/load-ods-data-workflow.ts
test/analytics/analytics-on-redshift/load-data-workflow/load-data-stepfuncs.json
test/analytics/analytics-on-redshift/load-data-workflow/load-data-stepfuncs.test.ts

fix: step function execution error when retry

---

src/control-plane/backend/lambda/api/common/types.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/service/stack.ts
src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
src/control-plane/backend/lambda/api/test/api/store.test.ts

fix: update pipeline from v1.0 version

---

src/control-plane/backend/stack-action-state-machine-construct.ts
test/control-plane/click-stream-api.test.ts

chore: grants permission to add tags to an IAM role

---

src/control-plane/backend/lambda/api/router/user.ts
src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
src/control-plane/backend/lambda/api/test/api/user.test.ts

fix: check user email when create/update user

---

frontend/src/pages/analytics/comps/ExploreDateRangePicker.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx

fix: remove duplicated time range and disable to reload when change time range

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
src/reporting/lambda/custom-resource/quicksight/index.ts
src/reporting/private/dashboard.ts
src/reporting/private/template-def.json
test/reporting/quicksight/lambda/quicksight-resource.test.ts

fix: analysis update fail when upgrade from 1.0 caused by id change

---

src/control-plane/auth/index.ts
src/control-plane/backend/lambda/api/middle-ware/auth-oidc.ts
test/control-plane/lambda/auth.test.ts

chore: return 403 when authentication exception

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts

chore: polish reporting code

---

frontend/src/pages/analytics/comps/ExploreDateRangePicker.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx
frontend/src/ts/utils.ts

chore: date range default value set to absolute pass 7days

---

src/alb-control-plane-stack.ts
src/cloudfront-control-plane-stack.ts
src/control-plane/auth/authorizer.ts
src/control-plane/auth/index.ts
src/control-plane/backend/click-stream-api.ts
src/control-plane/backend/lambda/api/middle-ware/auth-oidc.ts
test/control-plane/click-stream-api.test.ts
test/control-plane/lambda/auth.test.ts

fix: cache oidc conf error

---

frontend/src/components/eventselect/ConditionItem.tsx
frontend/src/components/eventselect/EventItem.tsx
frontend/src/context/reducer.ts
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/comps/AttributeGroup.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx

fix: add explore filter validation

---

frontend/src/components/layouts/AnalyticsNavigation.tsx
frontend/src/components/layouts/CustomBreadCrumb.tsx
frontend/src/components/layouts/Navigation.tsx
frontend/src/index.scss
frontend/src/pages/analytics/dashboard/AnalyticsDashboard.tsx
frontend/src/pages/home/comps/GetStarted.tsx
frontend/src/pages/projects/Projects.tsx
frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx

fix: use react router dom link instead of cloudscape link when navigating

---

src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/gtm/ServerDataConverter.java

fix: make fields protected in class

---

src/analytics/private/sqls/redshift/sp-migrate-ods-events-1.0-to-1.1.sql

fix: drop table error - table not exist

---

src/analytics/private/sqls/redshift/sp-migrate-ods-events-1.0-to-1.1.sql

----
- Tested the sql in redshift DB.

fix: wrong field name _channel in migration stored procedure

---

src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts
src/reporting/lambda/custom-resource/quicksight/index.ts
src/reporting/private/dashboard.ts

fix: can't delete temp QuickSight resources

---

frontend/public/locales/en-US/analytics.json
frontend/src/pages/analytics/metadata/event-parameters/MetadataParameterSplitPanel.tsx
frontend/src/pages/analytics/metadata/events/MetadataEventSplitPanel.tsx
frontend/src/pages/analytics/metadata/user-attributes/MetadataUserAttributeSplitPanel.tsx

chore: update metadata labels

---

src/analytics/private/sqls/redshift/sp-migrate-ods-events-1.0-to-1.1.sql

chore: add refesh materialized views after upgrade

---

src/analytics/private/sqls/redshift/dashboard/clickstream_event_parameter_view_v1.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_user_attr_view_v1.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_user_dim_view_v1.sql
src/control-plane/backend/lambda/api/service/reporting.ts
src/reporting/private/template-def.json

----
fix issue of Report can not show users info for GTM data

fix: builtin dashboard issues

---

docs/mkdocs.base.yml
docs/mkdocs.en.yml
docs/mkdocs.zh.yml

docs: add workshop link in nav tab

---

frontend/src/ts/const.ts

chore: optimize validate regular expression

---

src/analytics/private/sqls/redshift/sp-migrate-ods-events-1.0-to-1.1.sql

chore: refresh more MATERIALIZED views

---

frontend/src/pages/analytics/comps/SelectDashboardModal.tsx

fix: add refresh button in select dashboard modal

---

src/control-plane/backend/lambda/api/common/request-valid.ts
src/control-plane/backend/lambda/api/router/metadata.ts
src/control-plane/backend/lambda/api/router/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

chore: request projectId validate

---

src/control-plane/backend/lambda/api/middle-ware/error-handler.ts
src/control-plane/backend/lambda/api/test/api/app.test.ts

chore: catch invalid uri error

---

src/control-plane/backend/lambda/api/router/user.ts
src/control-plane/backend/lambda/api/test/api/user.test.ts

chore: validate user name length

---

frontend/src/pages/analytics/AnalyticsHome.tsx

fix: optimize redirect to dashboard when user had default app before

---

docs/en/pipeline-mgmt/data-processing/configure-execution-para.md
docs/zh/pipeline-mgmt/data-processing/configure-execution-para.md

docs: refine statements for config customized spark parameters

---

README.md
docs/en/sdk-manual/android.md
docs/en/sdk-manual/flutter.md
docs/en/sdk-manual/index.md
docs/en/sdk-manual/web.md
docs/mkdocs.en.yml
docs/mkdocs.zh.yml
docs/zh/sdk-manual/android.md
docs/zh/sdk-manual/flutter.md
docs/zh/sdk-manual/index.md
docs/zh/sdk-manual/swift.md
docs/zh/sdk-manual/web.md

docs: add flutter sdk

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/components/common/title/InfoTitle.tsx
frontend/src/pages/analytics/comps/ExploreDatePicker.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx

chore: update retention date picker

---

src/analytics/private/sqls/athena/clickstream-device-query.sql
src/analytics/private/sqls/athena/clickstream-event-parameter-query.sql
src/analytics/private/sqls/athena/clickstream-event-query.sql
src/analytics/private/sqls/athena/clickstream-lifecycle-daily-query.sql
src/analytics/private/sqls/athena/clickstream-lifecycle-weekly-query.sql
src/analytics/private/sqls/athena/clickstream-retention-query.sql
src/analytics/private/sqls/athena/clickstream-session-query.sql
src/analytics/private/sqls/athena/clickstream-user-attr-query.sql
src/analytics/private/sqls/athena/clickstream-user-dim-query.sql

fix: add hint of how to load Athena table latest partition

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/pages/analytics/dashboard/AnalyticsDashboard.tsx
frontend/src/pages/analytics/dashboard/detail/AnalyticsDashboardDetail.tsx

chore: i18n preset dashboard name and description

---

frontend/src/components/eventselect/comps/ItemsList.tsx

chore: search from label and name

---

.github/workflows/build-sub-projects.yml
.github/workflows/build.yml
.github/workflows/dist-scan.yml
.github/workflows/source-scan.yml
.projenrc.js

ci: enable merge queue support

---

.github/workflows/ghpage.yml

ci: add more actions to merge queue check

---

docs/en/deployment/with-oidc.md
docs/zh/deployment/with-oidc.md

docs: add signin into logincallbackurl

---

frontend/src/apis/analytics.ts
src/control-plane/backend/config/dictionary.json
src/control-plane/backend/lambda/api/model/metadata.ts
src/control-plane/backend/lambda/api/service/display.ts
src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
src/control-plane/backend/lambda/api/store/metadata-store.ts
src/control-plane/backend/lambda/api/test/api/metadata.test.ts

chore: add display name for event, event parameter and user attributes

---

src/reporting/lambda/custom-resource/quicksight/index.ts
src/reporting/private/dashboard.ts
src/reporting/private/template-def.json
src/reporting/quicksight-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts

fix: use dataset parameter to filter the events

---

src/common/constant.ts
src/control-plane/backend/lambda/api/common/request-valid.ts
src/control-plane/backend/lambda/api/router/user.ts
src/control-plane/backend/lambda/api/test/api/utils.test.ts
src/metrics-stack.ts
test/metrics/metrics-stack.test.ts

chore: email length limit

---

src/control-plane/backend/lambda/api/service/display.ts

chore: polish metadata display codes

---

frontend/src/components/layouts/AnalyticsHeader.tsx
frontend/src/components/layouts/Header.tsx

fix: reload page when user changes language manually

---

src/control-plane/backend/lambda/api/common/stack-params-valid.ts

chore: update prompt message for NAT check failure

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

fix: sql bug when only add user outer type condition

---

src/reporting/private/template-def.json

fix: bug in builtin dashboard template

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

fix: sql bug of user_pseudo_id join

---

frontend/src/pages/user/UserTable.tsx

fix: can not edit user name

---

frontend/src/context/reducer.ts
frontend/src/pages/analytics/analyzes/AnalyticsAnalyzes.tsx
frontend/src/pages/analytics/dashboard/AnalyticsDashboard.tsx
frontend/src/pages/analytics/data-management/AnalyticsDataManagement.tsx
frontend/src/pages/analytics/explore/AnalyticsExplore.tsx

fix: click info to show page introduce information

---

docs/mkdocs.base.yml

chore: update docs metrics sdk

---

src/control-plane/backend/lambda/api/common/request-valid.ts
src/control-plane/backend/lambda/api/router/metadata.ts
src/control-plane/backend/lambda/api/router/project.ts
src/control-plane/backend/lambda/api/service/metadata.ts
src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
src/control-plane/backend/lambda/api/test/api/metadata.test.ts
src/control-plane/backend/lambda/api/test/api/user.test.ts

chore: limit the input length of name and description

---

docs/en/troubleshooting.md
docs/zh/troubleshooting.md

docs: add resolution of deal with reporting stack deployment fail

---

src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/service/project.ts
src/control-plane/backend/lambda/api/test/api/project.test.ts

fix: able to delete project whose status is warning

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/components/eventselect/comps/AttributePreview.tsx
src/control-plane/backend/config/dictionary.json
src/control-plane/backend/lambda/api/service/display.ts
src/control-plane/backend/lambda/api/test/api/metadata.test.ts

----
1. Add miss parameter ua_os_version
2. All public parameters are preset
3. Modify the display format of category and show in frontend

chore: optimize metadata 

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts

fix: wrong condition when create visuals of rentention

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/components/layouts/AnalyticsHeader.tsx
frontend/src/pages/analytics/AnalyticsHome.tsx
frontend/src/types/project.d.ts
src/control-plane/backend/lambda/api/model/project.ts
src/control-plane/backend/lambda/api/service/project.ts
src/control-plane/backend/lambda/api/test/api/project.test.ts

fix: disable select project on analytic header

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

fix: sql logic of retention visuals

---

docs/en/plan-deployment/cost.md
docs/zh/plan-deployment/cost.md

----
update cost documents
update cost documents.

docs: update cost estimation

---

src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
src/control-plane/backend/lambda/api/test/api/workflow.test.ts

fix: error jars parameters when edit v1.0 pipeline

---

.github/workflows/ghpage.yml
.projenrc.js
package.json
src/control-plane/backend/lambda/api/package.json

chore: bump mainline version

---

.github/workflows/ghpage.yml

chore: support v1.1.0 docs release

---

.github/workflows/dist-scan.yml
.github/workflows/ghpage.yml

chore: fix release v1.1 doc

---

examples/web-sdk-sample/package.json
examples/web-sdk-sample/packages/vue2/package.json
examples/web-sdk-sample/yarn.lock

chore: upgrade web SDK demo package dependencies

---

src/control-plane/backend/Dockerfile

chore: exclude test when packaging backend

---

src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/DatasetUtil.java

fix: spark ETL jobs read/write same state file in parallel issue

---

examples/web-sdk-sample/README.md
examples/web-sdk-sample/packages/vue2/src/components/Websocket.vue
examples/web-sdk-sample/packages/vue2/src/utils/request.js

fix: web SDK demo typo and remove server time record in websocket

---

src/data-reporting-quicksight-stack.ts
src/reporting/lambda/custom-resource/quicksight/network-interface-check.ts
src/reporting/network-interface-check-custom-resource.ts
src/reporting/private/dashboard.ts
src/reporting/private/iam.ts
src/reporting/vpc-check-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
test/reporting/quicksight/lambda/network-interface-check.test.ts

fix: intermitent failure of creating data source of QuickSight

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

chore: optimize sql performance of explore

---

src/reporting/private/template-def.json

fix: wrong count method of user_pseudo_id in builtin dashboard

---

frontend/public/locales/en-US/pipeline.json
frontend/public/locales/zh-CN/pipeline.json
frontend/src/pages/pipelines/create/CreatePipeline.tsx
frontend/src/pages/pipelines/create/steps/BasicInformation.tsx
frontend/src/ts/init.ts
frontend/src/types/pipeline.d.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/store/aws/s3.ts
src/control-plane/backend/lambda/api/test/api/ddb-mock.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
src/control-plane/backend/lambda/api/test/api/workflow.test.ts

chore: check existence of the s3 bucket

---

src/control-plane/backend/lambda/api/service/stack.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts

fix: return pipeline details when execution no found

---

frontend/src/components/eventselect/AnalyticsType.ts
frontend/src/components/eventselect/reducer/analyticsEventSelectReducer.ts
frontend/src/pages/analytics/path/AnalyticsPath.tsx

fix: invalidation of event relation ship button

---

src/ingestion-server/custom-resource/update-alb-rules/index.ts

----
refactor code to match sonar policy
refactor code to match sonar policy

chore: polish updating ingestion configuration 

---

docs/en/sdk-manual/android.md
docs/en/sdk-manual/flutter.md
docs/en/sdk-manual/swift.md
docs/en/sdk-manual/web.md
docs/zh/sdk-manual/android.md
docs/zh/sdk-manual/flutter.md
docs/zh/sdk-manual/swift.md
docs/zh/sdk-manual/web.md

----
1. add items in android, swift, web and flutter SDK manual

docs: add items in Clickstream SDKs manual

---

docs/en/sdk-manual/http-api.md
docs/zh/sdk-manual/http-api.md

----
1. update table name in http api doc 

docs: update table name in http api

---

docs/en/troubleshooting.md
docs/en/upgrade.md
docs/zh/troubleshooting.md
docs/zh/upgrade.md
src/analytics/lambdas/custom-resource/create-schemas.ts
src/analytics/lambdas/redshift-data.ts
src/analytics/private/app-schema.ts
src/analytics/private/model.ts
src/analytics/private/sql-def.ts
test/analytics/analytics-on-redshift/lambda/custom-resources/create-schemas.test.ts

fix: redshift stack upgrade issue in UPDATE_ROLLBACK_FAILED

---

docs/en/troubleshooting.md
docs/zh/troubleshooting.md

docs: fix format issue in troubleshoting about stack upgrade failed

---

CHANGELOG.md

chore: update changelog for v1.1.1

---

src/service-catalog-appregistry-stack.ts

----
Fix AppRegistry stack description typo

chore: fix AppRegistry stack description typo

---

src/reporting/private/template-def.json

fix:  dashboard failed to render visuals when using distinct_count and small multiples

---

docs/en/troubleshooting.md
docs/zh/troubleshooting.md

docs: fix code snippet to create lambda handler

---

src/reporting/private/template-def.json

…d small multiples (#742)
----

fix: dashboard failed to render visuals when using distinct_count and small multiples

---

src/data-reporting-quicksight-stack.ts
src/reporting/lambda/custom-resource/quicksight/network-interface-check.ts
src/reporting/network-interface-check-custom-resource.ts
src/reporting/private/dashboard.ts
src/reporting/private/iam.ts
test/jestEnv.js
test/reporting/quicksight/lambda/network-interface-check.test.ts

fix: intermittent failure of creating data source of QuickSight

---

src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/service/stack.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts

chore: keep custom tags managed out of solution when updating pipeline

---

src/analytics/analytics-on-redshift.ts
src/analytics/private/app-schema.ts
src/main.ts
test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts

chore: refactor RedshiftSQLExecution to support specifying the function and properties

---

src/control-plane/backend/lambda/api/common/explore-types.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-bar-chart-multiple.json
src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-bar-chart.json
src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-funnel-chart.json
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

chore: improve performance of funnel visual

---

src/common/model.ts
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/store/aws/cloudformation.ts
src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
src/control-plane/backend/lambda/api/test/api/pipeline-status.test.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
src/control-plane/backend/lambda/listen-stack-status/listen-tools.ts
test/control-plane/lambda/listen-stack-status.test.ts

fix: pipeline status error when deleting project

---

src/reporting/private/template-def.json

fix: event attributes is null in builtin QuickSight dashboard activity and user sheet

---

frontend/src/components/layouts/AnalyticsHeader.tsx
frontend/src/components/layouts/AnalyticsNavigation.tsx
frontend/src/ts/const.ts

chore: keep the menu open after switch to another app in Analytics studio

---

README.md
e2e-deploy.sh
src/main.ts

chore: add script to deploy dev stack from existing or deleted stack

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/en-US/common.json
frontend/public/locales/zh-CN/analytics.json
frontend/public/locales/zh-CN/common.json
frontend/src/apis/analytics.ts
frontend/src/components/eventselect/reducer/AnalyticsEventSelect.tsx
frontend/src/index.scss
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/attribution/AnalyticsAttribution.tsx
frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
frontend/src/ts/explore-types.ts
frontend/src/types/analytics.d.ts
src/control-plane/backend/lambda/api/common/explore-types.ts
src/control-plane/backend/lambda/api/service/attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder-attribution.ts
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

feat: explore add attribution analytic

---

frontend/public/locales/en-US/pipeline.json
frontend/public/locales/zh-CN/pipeline.json
frontend/src/pages/pipelines/comps/BasicInfo.tsx
frontend/src/pages/pipelines/create/CreatePipeline.tsx
frontend/src/pages/pipelines/create/steps/BasicInformation.tsx
src/control-plane/backend/lambda/api/service/pipeline.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts

fix: validate tags empty key and value

---

e2e-deploy.sh

chore: append tags to e2e deploy command

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

----
change column alias to 'event_date' to align with template definition

fix: funnel bar chart can't render data

---

src/control-plane/backend/lambda/api/service/metadata.ts
src/control-plane/backend/lambda/api/test/api/metadata.test.ts

fix: manual trigger scan metadata

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/quicksight/templates/dashboard.json
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
src/reporting/private/dashboard.ts
src/reporting/private/template-def.json

----
1.unity week start day
2.funnel data miss match
3. extend time of waiting template new version creating finish

fix: funnel report issues

---

src/analytics/analytics-on-redshift.ts
src/common/constant.ts
src/control-plane/backend/click-stream-api.ts
test/control-plane/click-stream-api.test.ts

fix: miss policy for scan metadata

---

CHANGELOG.md

chore: update changelog for v1.1.2

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/pages/analytics/comps/SelectDashboardModal.tsx
frontend/src/pages/analytics/dashboard/AnalyticsDashboard.tsx
frontend/src/pages/analytics/dashboard/detail/AnalyticsDashboardDetail.tsx
frontend/src/types/analytics.d.ts
src/common/constant.ts
src/control-plane/backend/click-stream-api.ts
src/control-plane/backend/lambda/api/common/constants.ts
src/control-plane/backend/lambda/api/common/sdk-client.ts
src/control-plane/backend/lambda/api/common/stack-params-valid.ts
src/control-plane/backend/lambda/api/model/project.ts
src/control-plane/backend/lambda/api/service/project.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/control-plane/backend/lambda/api/store/click-stream-store.ts
src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
src/control-plane/backend/lambda/api/test/api/env.test.ts
src/reporting/lambda/custom-resource/quicksight/index.ts
src/reporting/private/dashboard.ts
src/reporting/private/iam.ts
test/control-plane/click-stream-api.test.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts
test/reporting/quicksight/lambda/quicksight-resource.test.ts

fix: can not list the dashboards created in analyze

---

docs/zh/analytics/dashboard/retention.md

docs: fix format of sql for zh dashboard retention

---

src/control-plane/backend/click-stream-api.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
test/control-plane/click-stream-api.test.ts

fix: error policy for list dashboard

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/en-US/help.json
frontend/public/locales/zh-CN/analytics.json
frontend/public/locales/zh-CN/help.json
frontend/src/components/eventselect/AnalyticsType.ts
frontend/src/components/eventselect/EventItem.tsx
frontend/src/components/eventselect/GroupSelectContainer.tsx
frontend/src/components/eventselect/reducer/AnalyticsEventSelect.tsx
frontend/src/components/eventselect/reducer/analyticsEventSelectReducer.ts
frontend/src/components/layouts/HelpInfo.tsx
frontend/src/index.scss
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/attribution/AnalyticsAttribution.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/ts/explore-types.ts
src/control-plane/backend/lambda/api/service/attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder-attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/templates/attribution-table-chart.json
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts

chore: add group select for analytics component

---

src/ingestion-server/server/parameter.ts

----
refactor ingestion server parameters
refactor ingestion server parameters

chore: refactor ingestion server parameters

---

src/reporting/lambda/custom-resource/quicksight/index.ts
test/reporting/quicksight/lambda/quicksight-resource.test.ts

fix: can' t delete app when folder contains custom resources

---

src/control-plane/backend/lambda/api/common/explore-types.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder-attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

fix: attribution analysis custom time window miss match

---

src/analytics/analytics-on-redshift.ts
src/analytics/lambdas/load-data-workflow/has-more-job-new.ts
src/analytics/lambdas/load-data-workflow/skip-running-workflow.ts
src/analytics/private/constant.ts
src/common/constant.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts
test/analytics/analytics-on-redshift/lambda/load-data/skip-running-workflow.test.ts

fix: warmup error sql

---

src/control-plane/backend/lambda/api/service/attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder-attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/templates/attribution-table-chart.json
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts

feat: add total conversion count to attribution visual

---

CHANGELOG.md

chore: update CHANGELOG for v1.1.3

---

src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/TransformerV2.java

chore: remove useless private field

---

src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

tests: fix unstable SQL builder test

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder-attribution.ts
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts

feat: support customize touch point name for attribution analysis

---

src/control-plane/backend/lambda/api/service/project.ts
src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-store.ts
src/control-plane/backend/lambda/api/test/api/project.test.ts

fix: delete project witch no pipeline

---

frontend/src/pages/pipelines/create/CreatePipeline.tsx
frontend/src/types/pipeline.d.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-check.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts

chore: polish code

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

feat: support select same event in event analysis

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

fix: event analysis data mismatch when have same events

---

src/control-plane/backend/lambda/api/service/attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder-attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

fix: path analysis error when page_title has single quotation marks

---

src/alb-control-plane-stack.ts
src/cloudfront-control-plane-stack.ts
src/control-plane/backend/click-stream-api.ts
src/control-plane/backend/event-bus-construct.ts
src/control-plane/backend/stack-action-state-machine-construct.ts
src/control-plane/backend/stack-workflow-state-machine-construct.ts
test/control-plane/cloudfront-control-plane-stack.test.ts
test/control-plane/test-utils.ts

fix: use CfnCondition generate policy prefix

---

src/ingestion-server/server/images/nginx/config/nginx.conf

chore: drop options request

---

src/control-plane/local/frontend.sh

chore: fix user pool client id in local dev script

---

src/alb-control-plane-stack.ts
src/base-lib/src/constant/constant.ts
src/cloudfront-control-plane-stack.ts
src/common/parameters.ts
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder-attribution.ts

chore: polish api code

---

frontend/src/pages/pipelines/create/steps/Reporting.tsx

chore: polish reporting ui

---

src/control-plane/backend/lambda/api/model/stacks.ts
src/control-plane/backend/lambda/api/service/attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder-attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
src/reporting/lambda/custom-resource/quicksight/index.ts
src/reporting/lambda/custom-resource/quicksight/network-interface-check.ts
src/reporting/parameter.ts
test/reporting/quicksight/lambda/network-interface-check.test.ts

feat: support query from shared redshift database

---

sonar-project.properties
src/common/s3-asset.ts
src/data-pipeline/data-pipeline.ts
src/streaming-ingestion-stack.ts

chore: polish s3-asset utility

---

src/analytics/lambdas/load-data-workflow/check-load-status.ts

----
simplify calculateWaitTime function

chore: simplify calculateWaitTime function

---

frontend/src/AppRouter.tsx
frontend/src/pages/analytics/analyzes/AnalyticsAnalyzes.tsx
frontend/src/pages/analytics/analyzes/full/AnalyticsAnalyzesFullWindow.tsx

chore: analyze full window

---

frontend/public/locales/en-US/pipeline.json
frontend/public/locales/zh-CN/pipeline.json
frontend/src/pages/pipelines/create/CreatePipeline.tsx
frontend/src/pages/pipelines/create/steps/DataProcessing.tsx
src/control-plane/backend/lambda/api/common/stack-params-valid.ts
src/control-plane/backend/lambda/api/test/api/utils.test.ts

fix: cron expressions error format

---

CHANGELOG.md

chore: update changelog for v1.1.5

---

src/control-plane/backend/lambda/listen-stack-status/index.ts
src/control-plane/backend/lambda/listen-stack-status/listen-tools.ts
test/control-plane/lambda/listen-stack-status.test.ts

fix: stack status error when update DDB conflict

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/pages/analytics/dashboard/create/CreateDashboard.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
src/base-lib/src/constant/constant.ts
src/control-plane/backend/lambda/api/common/request-valid.ts
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-check.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/control-plane/backend/lambda/api/test/api/utils.test.ts

chore: reject special characters in title when saving dashboard

---

src/analytics/lambdas/load-data-workflow/check-load-status.ts
src/analytics/lambdas/load-data-workflow/create-load-manifest.ts
src/analytics/lambdas/load-data-workflow/has-more-job-new.ts
src/analytics/lambdas/load-data-workflow/load-manifest-to-redshift.ts
src/analytics/lambdas/load-data-workflow/put-ods-source-to-store.ts
src/analytics/lambdas/sql-execution-sfn/sql-execution-step-fn.ts
src/analytics/private/load-ods-data-workflow.ts
src/common/workflow.ts
test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts
test/analytics/analytics-on-redshift/lambda/load-data/check-load-status.test.ts
test/analytics/analytics-on-redshift/lambda/load-data/create-manifest.test.ts
test/analytics/analytics-on-redshift/lambda/load-data/has-more-job-new.test.ts
test/analytics/analytics-on-redshift/lambda/load-data/load-manifest-to-redshift.test.ts
test/analytics/analytics-on-redshift/lambda/load-data/put-ods-source-to-store.test.ts
test/analytics/analytics-on-redshift/workflow/load-data-stepfuncs.json
test/analytics/analytics-on-redshift/workflow/load-data-stepfuncs.test.ts
test/analytics/analytics-on-redshift/workflow/load-data-sub-stepfuncs.json
test/jestEnv.js

fix: mitigate the load workflow to reach maximum events history limit

---

src/analytics/lambdas/user-segments-workflow/execute-segment-query.ts

chore: polish segments workflow

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/components/eventselect/AnalyticsType.ts
frontend/src/components/eventselect/EventItem.tsx
frontend/src/components/eventselect/reducer/AnalyticsEventSelect.tsx
frontend/src/components/eventselect/reducer/analyticsEventSelectReducer.ts
frontend/src/index.scss
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/attribution/AnalyticsAttribution.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/ts/explore-types.ts
frontend/src/types/analytics.d.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/quicksight/templates/event-pivot-table-chart-multiple.json
src/control-plane/backend/lambda/api/service/quicksight/templates/event-pivot-table-chart.json
src/control-plane/backend/lambda/api/service/quicksight/templates/event-table-chart.json
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

feat(explorative): add aggregation on event analysis

---

frontend/public/locales/en-US/pipeline.json
frontend/public/locales/zh-CN/pipeline.json
frontend/src/apis/pipeline.ts
frontend/src/pages/pipelines/create/steps/ReviewAndLaunch.tsx
frontend/src/pages/pipelines/detail/PipelineDetail.tsx
frontend/src/pages/pipelines/detail/comps/Processing.tsx
frontend/src/ts/url.ts
frontend/src/types/pipeline.d.ts
src/control-plane/backend/lambda/api/common/types.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/router/pipeline.ts
src/control-plane/backend/lambda/api/service/pipeline.ts
src/control-plane/backend/lambda/api/store/aws/sfn.ts
src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts

chore: pipeline detail show create schama status

---

src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

chore: won't create/update analyses when updating dashboard

---

frontend/src/index.scss
frontend/src/pages/analytics/comps/ExploreEmbedFrame.tsx

chore(UI): update iframe style for full window analyse

---

src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts
src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

chore: won't create/update analyses when creating dashboard

---

frontend/src/context/AnalyticsEventsContext.tsx
frontend/src/pages/analytics/analytics-utils.ts

chore: polish segment code

---

src/analytics/lambdas/load-data-workflow/load-manifest-to-redshift.ts

----
handle unsupported UTF8 data

chore: handle unsupported UTF8 data

---

src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ETLRunner.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/TransformerV3.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/model/ModelV2.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/Cleaner.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/DataConverterV3.java
src/data-pipeline/spark-etl/src/test/java/software/aws/solution/clickstream/TransformerV3Test.java
src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/session_parquet_schema.json
src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_gzip_event.json
src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_traffic_source_session.json
src/data-pipeline/spark-etl/src/test/resources/expected/schema-session.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_GTM_server_runner_v2_session.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_session.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_with_session_v2.json

fix(schema): ETL error for gzip data and session schema mismatch

---

src/analytics/private/sqls/redshift/user-m-view-v2.sql

fix(schema): missing comma in user-m-view definition

---

src/analytics/private/sqls/redshift/event-v2.sql
src/analytics/private/sqls/redshift/user-v2.sql

fix(schema): some typos in metadata comments

---

src/analytics/analytics-on-redshift.ts
src/analytics/lambdas/custom-resource/create-redshift-user.ts
src/analytics/lambdas/scan-metadata-workflow/scan-metadata.ts
src/analytics/private/constant.ts
src/analytics/private/model.ts
src/analytics/private/redshift-serverless.ts
src/analytics/private/scan-metadata-workflow.ts
src/analytics/private/sqls/redshift/sp-scan-metadata.sql
test/analytics/analytics-on-redshift/lambda/custom-resources/create-redshift-user.test.ts
test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/scan-metadata.test.ts

----
update sp scan metadata sql for v2 schema

chore(schema): update scan metadata for v2 schema

---

src/ingestion-server/kinesis-data-stream/kinesis-to-s3-lambda/index.ts

chore(schema): remove kds ingest_time override operation

---

frontend/src/index.scss

fix: analytics dropdown component style issue

---

src/analytics/lambdas/scan-metadata-workflow/scan-metadata.ts
src/analytics/private/constant.ts
test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/scan-metadata.test.ts

fix(schema): update sp scan metadata sql for v2 schema

---

.projenrc.js
frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
src/base-lib/src/constant/explore-types.ts
src/common/model.ts
src/control-plane/backend/Dockerfile
src/control-plane/backend/lambda/api/.gitignore
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/model/metadata.ts
src/control-plane/backend/lambda/api/service/display.ts
src/control-plane/backend/lambda/api/service/metadata.ts
src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
src/control-plane/backend/lambda/api/store/metadata-store.ts
src/control-plane/backend/lambda/api/test/api/metadata-mock.ts
src/control-plane/backend/lambda/api/test/api/metadata-v3.test.ts
src/control-plane/backend/lambda/api/test/api/metadata.test.ts

chore(schema): backend retrieve metadata from single truth

---

src/reporting/private/template-def.json

fix(schema): wrong filed name of retention visual

---

src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_traffic_source_user_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition_sp.sql
src/reporting/private/template-def.json

chore(schema): unify filter column name in dashboard definition

---

docs/en/faq.md
docs/zh/faq.md

docs: add faq how to view tables in redshift

---

src/control-plane/local/backend.sh

chore: add issuer environment to local backend shell

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/components/eventselect/AnalyticsType.ts
frontend/src/components/eventselect/ConditionItem.tsx
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/types/analytics.d.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-check.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

chore(schema): update explore API category and data type parameters for schema v2

---

src/reporting/lambda/custom-resource/quicksight/index.ts
test/reporting/quicksight/lambda/quicksight-resource.test.ts

chore: avoid reporting stack rollback fail

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-check.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder-attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
src/reporting/quicksight-custom-resource.ts

chore(schema): support timezone in explorative api

---

frontend/src/components/layouts/AnalyticsNavigation.tsx

chore: reset segments nav

---

frontend/src/apis/analytics.ts
frontend/src/pages/analytics/dashboard/AnalyticsDashboard.tsx
frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

chore: dashboard list page call warmup api

---

docs/en/sdk-manual/swift.md
docs/zh/sdk-manual/swift.md

----
1. update Swift SDK initialization configuration in SDK manual

docs: update Swift SDK initialization configuration in SDK manual

---

src/reporting/private/template-def.json

chore(schema): add detail sheet to builtin dashboard

---

src/control-plane/backend/lambda/api/service/stack.ts
src/control-plane/backend/lambda/api/test/api/application.test.ts

fix: error execution input when app update

---

examples/standalone-data-generator/application/shopping/ShoppingApp.py

----
1. fix example data generator user attributes shallow copy issue

chore(example): fix data generator user attributes shallow copy issue

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

fix: no data found in node path analysis

---

examples/standalone-data-generator/application/shopping/ShoppingApp.py

----
1. fix sampleAppEvent copy issue in example data generator

chore(example): fix sampleAppEvent copy issue in example data generator

---

src/analytics/private/sqls/redshift/dashboard/clickstream_retention_base_view.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_retention_view_v3.sql

chore(schema): modify SQL to handle abnormal data in retention view

---

README.md

----
1. add React Native SDK link in project readme

docs: add React Native SDK link in project readme

---

src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
src/control-plane/backend/lambda/sfn-workflow/index.ts
test/control-plane/lambda/sfn-workflow.test.ts

fix: pipeline execution callback bucket error

---

src/control-plane/backend/lambda/sfn-workflow/index.ts
test/control-plane/lambda/sfn-workflow.test.ts

fix: use console region as s3 region in workflow

---

src/control-plane/backend/layer/lambda-web-adapter/Dockerfile
src/control-plane/backend/layer/lambda-web-adapter/layer.ts

chore: upgrade adapter and check md5

---

src/control-plane/backend/lambda/api/test/api/segments/segments.test.ts

tests: improve stability of segments test

---

e2e-deploy.sh

chore: fix bug in local deploy script

---

src/control-plane/backend/lambda/api/test/api/segments/segments.test.ts

tests: fix unstable segment test

---

frontend/public/locales/en-US/application.json
frontend/public/locales/zh-CN/application.json
frontend/src/pages/application/create/comp/RegisterApp.tsx
frontend/src/pages/application/detail/ApplicationDetail.tsx
frontend/src/pages/application/detail/comp/ConfigReactNativeSDK.tsx
frontend/src/ts/guideConst.ts

chore: add react native detail

---

src/analytics/private/utils.ts

chore: polish analytics utils

---

sonar-project.properties

chore: exclude config files from duplications detection

---

src/analytics/private/sqls/redshift/dashboard/clickstream_event_view_v3.sql
src/reporting/private/dataset-col-def.ts
src/reporting/private/template-def.json
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts

chore(schema): add 'is_first_day_event' to base view

---

src/data-pipeline/utils/utils-role.ts
test/data-pipeline/data-pipeline-stack.test.ts

chore: grant the role with tagging glue resources permission

---

docs/en/upgrade.md
docs/zh/upgrade.md
src/analytics/private/sql-def.ts
src/analytics/private/sqls/redshift/fn-combine-json-list.sql
src/analytics/private/sqls/redshift/fn-parse-utm-from-url.sql
src/analytics/private/sqls/redshift/fn-rm-object-props.sql
src/analytics/private/sqls/redshift/fn-transform-event-custom-props.sql
src/analytics/private/sqls/redshift/fn-transform-user-custom-props.sql
src/analytics/private/sqls/redshift/sp-migrate-data-to-v2.sql
src/analytics/private/sqls/redshift/sp-migrate-event-to-v2.sql
src/analytics/private/sqls/redshift/sp-migrate-item-to-v2.sql
src/analytics/private/sqls/redshift/sp-migrate-session-to-v2.sql
src/analytics/private/sqls/redshift/sp-migrate-user-to-v2.sql

chore: stored procedures to migrate event to v2

---

src/data-pipeline/lambda/emr-serverless-app/index.ts
src/data-pipeline/utils/custom-resource.ts
test/data-pipeline/data-pipeline-stack.test.ts
test/data-pipeline/emr-serverless-app-cn.test.ts
test/data-pipeline/emr-serverless-app.test.ts

chore: add tags for emr serverless application

---

src/analytics/private/sqls/redshift/dashboard/clickstream_device_user_device_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_lifecycle_view_v2.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_lifecycle_weekly_view_v3.sql
src/reporting/private/template-def.json
src/reporting/quicksight-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts

chore(schema): fix bug in device and retention visuals

---

src/control-plane/backend/lambda/sfn-workflow/index.ts
test/control-plane/lambda/sfn-workflow.test.ts

fix: stack create error when pre stack output is null

---

docs/en/pipeline-mgmt/basic.md
docs/en/pipeline-mgmt/data-modeling/configure-data-modeling.md
docs/en/pipeline-mgmt/index.md
docs/en/pipeline-mgmt/vpc-prerequisites.md
docs/mkdocs.en.yml
docs/mkdocs.zh.yml
docs/zh/pipeline-mgmt/basic.md
docs/zh/pipeline-mgmt/data-modeling/configure-data-modeling.md
docs/zh/pipeline-mgmt/index.md
docs/zh/pipeline-mgmt/vpc-prerequisites.md

docs: add basic configuration of pipeline

---

src/control-plane/backend/click-stream-api.ts
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
src/control-plane/backend/lambda/api/test/api/workflow.test.ts
src/control-plane/backend/lambda/listen-stack-status/listen-tools.ts

fix: pipeline create failed with role prefix 

---

src/control-plane/backend/click-stream-api.ts
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts
src/control-plane/backend/lambda/api/test/api/workflow.test.ts
src/control-plane/backend/lambda/listen-stack-status/listen-tools.ts

fix: pipeline create failed with role prefix

---

src/analytics/private/sqls/redshift/dashboard/clickstream_device_user_device_sp.sql

fix: type error in user device sp

---

src/analytics/private/sqls/redshift/dashboard/clickstream_retention_base_view.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_retention_view_v3.sql
src/reporting/private/template-def.json
src/reporting/quicksight-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts

chore: update intra-day user and retention visuals

---

frontend/public/locales/en-US/common.json
frontend/public/locales/zh-CN/common.json
frontend/src/AppRouter.tsx
frontend/src/apis/segments.ts
frontend/src/components/layouts/AnalyticsNavigation.tsx
frontend/src/context/SegmentContext.tsx
frontend/src/pages/analytics/segments/AddUserSegment.tsx
frontend/src/pages/analytics/segments/UserSegments.tsx
frontend/src/pages/analytics/segments/components/SegmentEditor.tsx
frontend/src/ts/request.ts
frontend/test/components/segments/SegmentGroup.test.tsx
src/base-lib/src/model/segment.ts
src/control-plane/backend/click-stream-api.ts
src/control-plane/backend/lambda/api/service/segments/segment.ts

feat(segments): add segments duplicate and edit

---

docs/en/deployment/index.md
docs/en/deployment/with-oidc.md
docs/en/resources/aws-china-prerequisites.md
docs/mkdocs.en.yml
docs/mkdocs.zh.yml
docs/zh/deployment/index.md
docs/zh/deployment/with-oidc.md
docs/zh/resources/aws-china-prerequisites.md

docs: add AWS China prerequisites

---

frontend/src/pages/analytics/path/AnalyticsPath.tsx
src/base-lib/src/constant/explore-types.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

chore(schema): path analysis update

---

.github/workflows/source-scan.yml

chore: update git-secrets install in ci workflow

---

.github/workflows/source-scan.yml

ci: update git-secrets install in ci workflow

---

src/data-pipeline/utils/utils-lambda.ts
test/data-pipeline/data-pipeline-stack.test.ts

fix: EMR job submitter lambda role for config rule file

---

src/data-pipeline/utils/utils-lambda.ts
test/data-pipeline/data-pipeline-stack.test.ts

fix: EMR job submitter lambda role for config rule files

---

src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts

fix: truncate rule and topic name

---

src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/UAEnrichHelper.java
src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/UAEnrichHelperTest.java

fix: null pointer exception when parse UA

---

.projenrc.js
package.json
src/common/s3-asset.ts
src/control-plane/backend/click-stream-api.ts
src/control-plane/backend/layer/lambda-web-adapter/layer.ts
src/control-plane/cloudfront-s3-portal.ts
test/jestEnv.js

chore: use local env variables skip assets build

---

frontend/src/pages/pipelines/create/CreatePipeline.tsx
frontend/src/pages/pipelines/detail/comps/Processing.tsx
frontend/src/pages/plugins/comps/PluginTable.tsx
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts

fix: no plugin display in detail page in some cases

---

frontend/src/pages/user/CreateUser.tsx

fix: clean state when close create user modal

---

e2e-deploy.sh
src/main.ts

chore: optimize the performance when deploying/synthesizing specific stack

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder-attribution.ts
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts

fix: attribution analysis sql error

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/quicksight/templates/filter-group-relative.template
src/control-plane/backend/lambda/api/service/quicksight/templates/filter-group.template
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
src/reporting/private/dashboard.ts

fix: fail to save dashboard

---

src/analytics/private/sqls/redshift/dashboard/clickstream_device_crash_rate_sp.sql
src/reporting/private/template-def.json

fix: crash rate is always zero

---

src/data-reporting-quicksight-stack.ts
src/reporting/parameter.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts

chore: update QuickSight datasource db name

---

README.md

chore: update e2e-deploy usage

---

src/analytics/lambdas/scan-metadata-workflow/store-metadata-into-ddb.ts
src/base-lib/src/constant/constant.ts
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/store/dynamodb/dynamodb-metadata-store.ts
src/control-plane/backend/lambda/api/test/api/metadata-mock.ts
src/control-plane/backend/lambda/api/test/api/metadata-v3.test.ts
src/control-plane/backend/lambda/api/test/api/metadata.test.ts
test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/store-metadata-into-ddb.test.ts

----
add version to metadata
@tyyzqmf also need to refactor control plane backend to read version
integration test and UT

chore: add version to metadata

---

src/data-pipeline/utils/custom-resource.ts
test/data-pipeline/data-pipeline-stack.test.ts

fix: EMR application delete error

---

frontend/src/components/layouts/Footer.tsx

chore: footer add control plane stack link

---

frontend/public/locales/en-US/application.json
frontend/public/locales/zh-CN/application.json
frontend/src/index.scss
frontend/src/pages/analytics/dashboard/create/CreateDashboard.tsx
frontend/src/pages/application/detail/comp/ConfigReactNativeSDK.tsx
frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx
frontend/src/ts/guideConst.ts

----
- update RN sdk desc
- app list show timezone
- disable close modal when creating dashboard
- dropdown button css style

chore: UI optimization

---

.projenrc.js
pnpm-lock.yaml
src/analytics/lambdas/custom-resource/create-schemas.ts
src/analytics/lambdas/scan-metadata-workflow/scan-metadata.ts
src/analytics/private/model.ts
src/analytics/private/sqls/redshift/event-v2.sql
src/base-lib/.projen/deps.json
src/base-lib/.projen/tasks.json
src/base-lib/package.json
src/base-lib/src/common/utils.ts
src/base-lib/src/constant/constant.ts
src/base-lib/src/constant/explore-types.ts
src/control-plane/backend/lambda/api/common/utils.ts

chore: render category in sql

---

frontend/src/pages/analytics/comps/AttributeGroup.tsx

chore: edit style of group select component

---

frontend/src/pages/analytics/traffic-source/modal/SourceCategoryModal.tsx

fix: show pattern only source category is Search

---

src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_device_user_device_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_kpi_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_event_view_v3.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_lifecycle_weekly_view_v3.sql
src/reporting/private/dataset-col-def.ts
src/reporting/private/template-def-spice.json
src/reporting/private/template-def.json
src/reporting/quicksight-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts

fix: improve engagement time accuracy in edge case

---

src/base-lib/src/common/sdk-client-config.ts
src/control-plane/backend/lambda/sfn-action/index.ts
src/control-plane/backend/lambda/sfn-workflow/index.ts

chore: increase timeout in step function lambda for CFN SDK

---

src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/ClickstreamEventParser.java
src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/gtm/GTMEventParser.java
src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_disable_time_shift.json
src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event.json
src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event_v2.json
src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event_web.json
src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_time_shift.json
src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_zip_event_v2.json
src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/etl_runner_v3_event1.json
src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_event.json
src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_event_max_len2.json
src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_gzip_event.json
src/data-pipeline/spark-etl/src/test/resources/event_v2/expected/transform_v3_traffic_source_event.json
src/data-pipeline/spark-etl/src/test/resources/expected/test_convert_data_v3.json

fix: ingest time loses when transforming the raw data

---

src/analytics/private/sqls/redshift/sp-scan-metadata.sql

fix: long field value causes scanning workflow failure

---

frontend/src/pages/analytics/traffic-source/TrafficSourceHome.tsx

chore: add space between traffic source tables

---

.projenrc.js
package.json
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

fix: reduce warmup waiting time avoid timeout

---

.github/workflows/dist-scan.yml
.github/workflows/sonarqube/quality-gate.json
.github/workflows/sonarqube/sonar-configure.sh
buildspec.yml
deployment/run-unit-tests.sh
sonar-project.properties

ci: add sonar scan

---

src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_country_new_user_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_traffic_source_user_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition_sp.sql
src/reporting/private/template-def-spice.json
src/reporting/private/template-def.json

fix: dashboard issues polish

---

src/analytics/private/sqls/redshift/sp-clear-expired-data.sql

----
clean clickstream log history data

chore: clean clickstream log history data

---

buildspec.yml

ci: fix script error in codebuild

---

frontend/src/ts/utils.ts

fix: moment import

---

README.md

docs: add Local build spark ETL jar

---

frontend/src/pages/application/create/comp/RegisterApp.tsx
frontend/src/pages/application/detail/ApplicationDetail.tsx
frontend/src/pages/pipelines/detail/comps/Ingestion.tsx
frontend/src/ts/utils.ts

chore: timezone add UTC offset and stop ping private ALB

---

frontend/src/pages/analytics/segments/UserSegmentDetails.tsx
frontend/src/pages/analytics/segments/UserSegments.tsx

----
Fix sonarqube issues for segments

chore: polish segments ui

---

.github/workflows/dist-scan.yml
deployment/run-unit-tests.sh
docs/mkdocs.base.yml

ci: improve sonar scan

---

src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_traffic_source_user_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_view_cnt_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_event_base_view_sp.sql

----
miss data in SPs:
clickstream_base_event_view
clickstream_acquisition_day_traffic_source_user
clickstream_acquisition_day_user_view_cnt

fix: event base view miss data

---

src/analytics/analytics-on-redshift.ts
src/analytics/parameter.ts
src/analytics/private/refresh-materialized-views-workflow.ts
src/data-analytics-redshift-stack.ts
test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts

----
add RefreshMode parameter

chore: add RefreshMode parameter

---

src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/service/stack.ts
src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
src/control-plane/backend/lambda/api/test/api/workflow.test.ts

fix: add reporting stack with action error

---

frontend/src/apis/analytics.ts
frontend/src/pages/analytics/dashboard/detail/AnalyticsDashboardDetail.tsx
src/control-plane/backend/lambda/api/common/sdk-client.ts
src/control-plane/backend/lambda/api/service/project.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/analytics-dashboard.test.ts
src/control-plane/backend/lambda/api/test/api/reporting.test.ts

chore: wait warmup on dashboard detail page

---

.github/workflows/dist-scan.yml

ci: login public ecr to mitigate api throttle

---

src/data-pipeline/lambda/emr-job-submitter/traffic_source_category_rule_v1.ts

chore: update traffic source category rules

---

docs/en/pipeline-mgmt/vpc-prerequisites.md
docs/zh/pipeline-mgmt/vpc-prerequisites.md

docs: emphasize using gateway endpoints for DynamoDB

---

src/analytics/private/sqls/redshift/sp-clear-expired-data.sql

----
remove user table operation in clear history data sp

chore: remove user table operation in clear history data sp

---

src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts

chore: adjust EMR initialExecutors for large volume data 

---

src/analytics/private/sqls/redshift/clickstream-log.sql

fix: change max length of log table columns

---

src/analytics/lambdas/custom-resource/create-schemas.ts
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_kpi_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_retention_user_new_return_sp.sql
src/reporting/private/template-def-spice.json
src/reporting/private/template-def.json
src/reporting/quicksight-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts

fix: sql bugs in device and engagement sheet

---

src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts
src/control-plane/backend/lambda/api/test/api/workflow-version.test.ts

fix: error tags when update pipeline

---

src/analytics/private/constant.ts
src/analytics/private/sql-def.ts
src/analytics/private/sqls/redshift/clickstream-log-v2.sql
src/analytics/private/sqls/redshift/sp-clickstream-log-non-atomic.sql
src/analytics/private/sqls/redshift/sp-clickstream-log.sql

----
create clickstream log v2 table

chore: create clickstream log v2 table

---

src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/BaseEventParser.java
src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event.json
src/data-pipeline/etl-common/src/test/resources/expected/test_parse_line_to_db_row_event_web.json
src/data-pipeline/etl-common/src/test/resources/gtm-server/expected/test_gtm_parseLineToDBRow_event.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_GTM_server_runner_v2_event_v2.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_no_js_client_id_v2.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_session_start1_v2.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_session_start2_v2.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_single_data_v2.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_user_data_user_props_v2.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_convert_user_data_v2.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_brand_v2.json
src/data-pipeline/spark-etl/src/test/resources/gtm-server/expected/test_transform_data_session_start_v2.json

fix: keep url root path

---

src/analytics/lambdas/custom-resource/create-schemas.ts
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_kpi_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_retention_user_new_return_sp.sql
src/reporting/private/template-def-spice.json
src/reporting/private/template-def.json
src/reporting/quicksight-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts

----
cherry pick 
#1304 
#1306 

fix: sql bugs in device and engagement sheet 

---

src/reporting/lambda/custom-resource/quicksight/index.ts
src/reporting/private/template-def-spice.json
src/reporting/private/template-def.json

fix: app crash rate overtime visual incorrect config

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/en-US/help.json
frontend/public/locales/zh-CN/analytics.json
frontend/public/locales/zh-CN/help.json
frontend/src/hooks/useFetchEvents.ts
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/traffic-source/modal/SourceCategoryModal.tsx

----
- do not fetch api when id is null
- source categories cannot be duplicate
- update the attribution help info

chore: update ui 

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/en-US/help.json
frontend/public/locales/zh-CN/analytics.json
frontend/public/locales/zh-CN/help.json
frontend/src/hooks/useFetchEvents.ts
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/traffic-source/modal/SourceCategoryModal.tsx

chore: update ui

---

.github/workflows/ghpage.yml

chore: exclude dev doc deployment

---

src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_page_screen_view_detail.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_page_screen_view_detail_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_page_screen_view_sp.sql
src/main.ts
src/reporting/lambda/custom-resource/quicksight/index.ts
src/reporting/private/dashboard.ts
src/reporting/private/template-def-spice.json
src/reporting/private/template-def.json
src/reporting/quicksight-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts

fix: page view count mismatch

---

src/analytics/lambdas/scan-metadata-workflow/scan-metadata.ts
src/analytics/lambdas/scan-metadata-workflow/store-metadata-into-ddb.ts
src/analytics/private/scan-metadata-workflow.ts
src/analytics/private/sqls/redshift/event-v2.sql
src/analytics/private/sqls/redshift/session.sql
src/analytics/private/sqls/redshift/sp-scan-metadata.sql
src/analytics/private/sqls/redshift/user-v2.sql
src/control-plane/backend/Dockerfile
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/test/api/metadata-v3.test.ts
test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/scan-metadata.test.ts
test/analytics/analytics-on-redshift/lambda/scan-metadata-workflow/store-metadata-into-ddb.test.ts

----
optimize scan metadata performance

chore: optimize scan metadata performance

---

src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ETLRunner.java

chore: avoid output a lot of small files in ETL

---

src/analytics/private/sqls/redshift/sp-merge-event-v2.sql
src/analytics/private/sqls/redshift/sp-merge-item-v2.sql
src/analytics/private/sqls/redshift/sp-merge-session.sql
src/analytics/private/sqls/redshift/sp-merge-user-v2.sql

----
remove update created_time operation and set it in INSERT operation.

chore: optimize merge performance

---

src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ETLRunner.java

fix: improve ETL performance

---

src/analytics/private/load-ods-data-workflow.ts
test/analytics/analytics-on-redshift/data-analytics-redshift-stack.test.ts

chore: increase timeout to handle large ods file number

---

frontend/config/webpack.config.js
src/alb-control-plane-stack.ts
src/control-plane/frontend/Dockerfile

fix: build aarch64 frontend image

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/en-US/common.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/index.scss
frontend/src/pages/analytics/comps/ExploreEmbedFrame.tsx
frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
frontend/src/ts/request.ts
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts

chore: old pipeline allowed to access dashboard

---

frontend/config/webpack.config.js

chore: fix frontend local start

---

src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_country_new_user_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_kpi.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_kpi_sp.sql
src/control-plane/backend/lambda/api/service/attribution.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/quicksight/templates/event-bar-chart-multiple.json
src/control-plane/backend/lambda/api/service/quicksight/templates/event-bar-chart.json
src/control-plane/backend/lambda/api/service/quicksight/templates/event-line-chart-multiple.json
src/control-plane/backend/lambda/api/service/quicksight/templates/event-line-chart.json
src/control-plane/backend/lambda/api/service/quicksight/templates/event-pivot-table-chart-multiple.json
src/control-plane/backend/lambda/api/service/quicksight/templates/event-pivot-table-chart.json
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts
src/reporting/private/template-def-spice.json
src/reporting/private/template-def.json
src/reporting/quicksight-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts

fix: analysis on event property is not in the expected data format

---

docs/en/troubleshooting.md
docs/zh/troubleshooting.md

docs: add troubleshoot for failing to create emr application in the specified subnets

---

frontend/src/pages/analytics/explore/AnalyticsExplore.tsx

chore: explore display empty if pipeline short version not latest 

---

frontend/src/pages/analytics/explore/AnalyticsExplore.tsx

chore: explore display empty if pipeline short version not latest

---

frontend/src/components/pipeline/PipelineStatus.tsx
frontend/src/pages/application/detail/ApplicationDetail.tsx
frontend/src/pages/pipelines/comps/BasicInfo.tsx
frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx

chore: pipeline status auto refresh

---

frontend/src/components/pipeline/PipelineStatus.tsx
frontend/src/pages/application/detail/ApplicationDetail.tsx
frontend/src/pages/pipelines/comps/BasicInfo.tsx
frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx

chore: pipeline status auto refresh 

---

src/reporting/private/template-def-spice.json
src/reporting/private/template-def.json

chore: add data point count setting

---

docs/en/faq.md
docs/zh/faq.md

docs: add faq for how implementing redshift data sharing

---

src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java

fix: traffic source medium

---

frontend/src/ts/url.ts

chore: update doc url 

---

frontend/src/ts/url.ts

chore: update doc url

---

docs/en/faq.md
docs/zh/faq.md

docs: update data sharing

---

CHANGELOG.md

chore: update CHANGELOG for 1.1.6

---

src/analytics/private/sqls/redshift/dashboard/clickstream_event_base_view_sp.sql
src/base-lib/src/constant/dashboard.ts

fix: data can't be updated to base view when using custom time range

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts

fix: attribution analysis failed when specify fixed time range

---

docs/en/upgrade.md
docs/zh/upgrade.md

docs: update migration data procedures

---

docs/en/faq.md
docs/zh/faq.md

docs: fix data share sql

---

src/analytics/private/sqls/redshift/sp-merge-session.sql

fix: mitigate the duplicated sessions

---

src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/ETLRunner.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/TransformerV3.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/BaseThirdPartyTransformer.java
src/data-pipeline/spark-etl/src/main/java/software/aws/solution/clickstream/transformer/BaseTransformerV3.java
test/data-pipeline/emr-job-submitter.test.ts

chore: EMR cost optimization for small data

---

src/analytics/private/sqls/redshift/sp-clear-expired-data.sql

chore: remove uesless log in clear expire data sp

---

src/data-pipeline/lambda/emr-job-submitter/emr-client-util.ts

chore: polish emr job submitting

---

src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

chore: explore analysis performance improvement

---

src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_country_new_user_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_traffic_source_user_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_view_cnt_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_device_crash_rate_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_device_user_device_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_day_event_view_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_entrance_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_event_name_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_exit_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_kpi_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_page_screen_view_detail_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_engagement_page_screen_view_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_event_base_view_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_retention_dau_wau_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_retention_event_overtime_sp.sql
src/analytics/private/sqls/redshift/dashboard/clickstream_retention_user_new_return_sp.sql

chore: change user/event count computing method

---

src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/Util.java
src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java
src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/util/UtilTest.java

fix: enhance traffic source

---

src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/Util.java
src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java
src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/util/UtilTest.java

fix: unable to parse custom traffic source with illegal characters

---

src/control-plane/backend/lambda/sfn-action/index.ts
test/control-plane/lambda/sfn-action.test.ts

fix: upgrade pipeline with deleted paramters

---

frontend/src/AppRouter.tsx
frontend/src/index.scss
frontend/src/pages/alarms/AlarmList.tsx
frontend/src/pages/analytics/AnalyticsHome.tsx
frontend/src/pages/analytics/analyzes/AnalyticsAnalyzes.tsx
frontend/src/pages/analytics/dashboard/AnalyticsDashboard.tsx
frontend/src/pages/analytics/dashboard/detail/AnalyticsDashboardDetail.tsx
frontend/src/pages/analytics/data-management/AnalyticsDataManagement.tsx
frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
frontend/src/pages/analytics/realtime/AnalyticsRealtime.tsx
frontend/src/pages/analytics/segments/AddUserSegment.tsx
frontend/src/pages/analytics/segments/UserSegmentDetails.tsx
frontend/src/pages/analytics/segments/UserSegments.tsx
frontend/src/pages/application/create/CreateApplication.tsx
frontend/src/pages/application/detail/ApplicationDetail.tsx
frontend/src/pages/home/Home.tsx
frontend/src/pages/pipelines/create/CreatePipeline.tsx
frontend/src/pages/pipelines/detail/PipelineDetail.tsx
frontend/src/pages/plugins/PluginList.tsx
frontend/src/pages/plugins/create/CreatePlugin.tsx
frontend/src/pages/projects/Projects.tsx
frontend/src/pages/projects/detail/ProjectDetail.tsx
frontend/src/pages/user/UserList.tsx
frontend/src/pages/user/UserTable.tsx

fix: ui layout issue after upgrade cloudscape

---

src/control-plane/backend/lambda/api/middle-ware/auth-oidc.ts
src/control-plane/backend/lambda/api/test/api/auth.test.ts

fix: no authentication required for health check

---

src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
src/data-pipeline/etl-common/src/test/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelperTest.java

fix: medium of traffic source

---

frontend/src/pages/analytics/explore/AnalyticsExplore.tsx

fix: Explorations are incorrectly disabled

---

src/control-plane/backend/lambda/api/service/stack.ts
src/control-plane/backend/lambda/api/test/api/pipeline-mock.ts
src/control-plane/backend/lambda/api/test/api/workflow.test.ts

fix: retry upgrading failure does not work

---

frontend/src/ts/utils.ts

fix: editing pipeline causes illegal version string error

---

src/analytics/private/sqls/redshift/dashboard/clickstream_acquisition_day_user_acquisition_sp.sql

fix: incorrect active user count in acquisition sheet

---

src/data-pipeline/utils/custom-resource.ts
test/data-pipeline/data-pipeline-stack.test.ts

fix: EMR server-less application upgrade

---

frontend/src/pages/projects/comps/SplitPanel.tsx
src/control-plane/backend/lambda/api/model/stacks.ts

fix: project edit error and allow DevMode change

---

frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx

fix: stream enable and disable button

---

src/analytics/private/sqls/redshift/sp-merge-event-v2.sql
src/analytics/private/sqls/redshift/sp-merge-item-v2.sql
src/analytics/private/sqls/redshift/sp-merge-session.sql
src/analytics/private/sqls/redshift/sp-merge-user-v2.sql

chore: optimize ODS data load

---

src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/BaseEventParser.java
src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/RuleBasedTrafficSourceHelper.java
src/data-pipeline/etl-common/src/main/java/software/aws/solution/clickstream/common/enrich/ts/rule/ChannelListEvaluator.java

fix: traffic source cache

---

src/control-plane/backend/event-bus-construct.ts
src/control-plane/backend/lambda/api/service/quicksight/reporting-utils.ts
src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-bar-chart-multiple.json
src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-bar-chart.json
src/control-plane/backend/lambda/api/service/quicksight/templates/funnel-funnel-chart.json
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

chore: funnel visual performance improvement

---

src/streaming-ingestion/flink-etl/build.gradle
src/streaming-ingestion/flink-etl/src/test/java/software/aws/solution/clickstream/flink/BaseFlinkTest.java

tests: fix OOM error when running tests in Flink ETL

---

frontend/src/apis/analytics.ts
frontend/src/components/common/ExtendIcon.tsx
frontend/src/components/layouts/AnalyticsNavigation.tsx
frontend/src/pages/analytics/realtime/AnalyticsRealtime.tsx
frontend/src/types/pipeline.d.ts
src/control-plane/backend/lambda/api/common/types.ts
src/control-plane/backend/lambda/api/middle-ware/auth-role.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/router/project.ts
src/control-plane/backend/lambda/api/service/project.ts
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/store/aws/quicksight.ts

feat: realtime dashboard embbeding

---

src/reporting/lambda/custom-resource/quicksight/index.ts
test/reporting/quicksight/lambda/quicksight-resource.test.ts

fix: dashboard name miss match

---

frontend/public/locales/en-US/pipeline.json
frontend/public/locales/zh-CN/pipeline.json
frontend/src/components/common/ExtendIcon.tsx
frontend/src/components/layouts/AnalyticsNavigation.tsx
frontend/src/pages/analytics/realtime/AnalyticsRealtime.tsx
frontend/src/pages/pipelines/detail/comps/Ingestion.tsx
frontend/src/pages/pipelines/detail/comps/Processing.tsx
frontend/src/types/pipeline.d.ts
src/control-plane/backend/lambda/api/common/types.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/service/pipeline.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts

----
1. Save switch status when refresh realtime page
2. Add streaming info and schema status
3. Update pipeline creation wording and real-time UI
4. Fix realtime page repeatedly loads

fix: issues of real-time UI

---

frontend/public/locales/en-US/analytics.json
frontend/public/locales/zh-CN/analytics.json
frontend/src/components/eventselect/AnalyticsType.ts
frontend/src/components/eventselect/ConditionItem.tsx
frontend/src/components/eventselect/reducer/analyticsSegmentFilterReducer.ts
frontend/src/components/eventselect/reducer/analyticsSegmentGroupReducer.ts
frontend/src/pages/analytics/analytics-utils.ts
frontend/src/pages/analytics/attribution/AnalyticsAttribution.tsx
frontend/src/pages/analytics/event/AnalyticsEvent.tsx
frontend/src/pages/analytics/explore/AnalyticsExplore.tsx
frontend/src/pages/analytics/funnel/AnalyticsFunnel.tsx
frontend/src/pages/analytics/path/AnalyticsPath.tsx
frontend/src/pages/analytics/retention/AnalyticsRetention.tsx
frontend/src/pages/analytics/segments/UserSegmentDetails.tsx
frontend/src/pages/analytics/segments/components/SegmentEditor.tsx
frontend/test/utils/analytics-utils.test.ts
src/base-lib/src/constant/explore-types.ts
src/base-lib/src/model/segment.ts
src/control-plane/backend/lambda/api/router/segment.ts
src/control-plane/backend/lambda/api/service/segments/segment.ts
src/control-plane/backend/lambda/api/service/segments/user-segments-sql.ts

----
1. Integrate user segment with analytics explore
2. Fix segment UI bugs

feat: integrate user segment with analytics explore

---

src/reporting/private/template-def-spice.json
src/reporting/private/template-def.json
src/reporting/quicksight-custom-resource.ts
test/reporting/quicksight/data-reporting-quicksight-stack.test.ts

fix: day_diff data type missmatch

---

src/control-plane/backend/lambda/api/service/quicksight/sql-builder.ts
src/control-plane/backend/lambda/api/test/api/attribution-sql-builder.test.ts
src/control-plane/backend/lambda/api/test/api/sql-builder.test.ts

fix: segment filter doesn't work in explorative analysis

---

buildspec.yml
solution-manifest.yaml

chore: add solution-manifest

---

frontend/public/locales/en-US/pipeline.json
frontend/public/locales/zh-CN/pipeline.json
frontend/src/apis/resource.ts
frontend/src/pages/pipelines/create/CreatePipeline.tsx
frontend/src/pages/pipelines/create/steps/ConfigIngestion.tsx
frontend/src/pages/pipelines/create/steps/DataProcessing.tsx
frontend/src/pages/projects/detail/comp/ProjectPipeline.tsx
frontend/src/ts/init.ts
frontend/src/ts/utils.ts
frontend/src/types/pipeline.d.ts
frontend/test/msk-redshift.test.tsx
frontend/test/service-available.test.tsx
frontend/test/update-pipeline.test.tsx
src/base-lib/src/constant/constant.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/model/stacks.ts
src/control-plane/backend/lambda/api/service/application.ts
src/control-plane/backend/lambda/api/store/aws/cloudformation.ts
src/control-plane/backend/lambda/api/store/aws/flink.ts
src/control-plane/backend/lambda/api/test/api/application.test.ts
src/control-plane/backend/lambda/api/test/api/workflow-mock.ts
src/control-plane/backend/lambda/api/test/api/workflow.test.ts
src/streaming-ingestion-stack.ts
src/streaming-ingestion/parameter.ts
src/streaming-ingestion/private/constant.ts
src/streaming-ingestion/private/kinesis-sink.ts
src/streaming-ingestion/private/utils.ts
test/streaming-ingestion/streaming-ingestion-stack.test.ts

----
1. Ping flink service resources
2. Run flink when app streming enable
3. Stop flink when all app streming disable
4. Check transformer type for streaming

chore: streaming module polish

---

deployment/build-s3-dist.sh
deployment/cdk-solution-helper/index.js
deployment/solution_config

----
Already build and create pipeline with built template.

ci: publish container images to ECR public

---

deployment/build-s3-dist.sh

ci: fix build runtime error

---

package.json
pnpm-lock.yaml

fix: upgrade esbuild to resolve lambda runtime package not found error

---

docs/en/getting-started/3.integrate-sdk.md
docs/zh/getting-started/3.integrate-sdk.md

----
1. revised the SDK integration steps in the getting started section

docs: revised the SDK integration steps in the getting started section

---

frontend/src/ts/const.ts
frontend/src/ts/utils.ts
src/base-lib/src/constant/constant.ts
src/control-plane/backend/lambda/api/common/request-valid.ts
src/control-plane/backend/lambda/api/router/application.ts
src/control-plane/backend/lambda/api/test/api/application.test.ts

chore: validate timezone input when creating application

---

src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/realtime.test.ts

fix: realtime embedding error

---

docs/en/pipeline-mgmt/ingestion/configure-ingestion-endpoint.md
docs/zh/pipeline-mgmt/ingestion/configure-ingestion-endpoint.md

----
add fargate in ingestion part
Preview:

docs: add fargate type in ingestion server

---

frontend/src/pages/common/Tags.tsx
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/service/stack.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts

fix: able to delete built-in tags when editing pipeline

---

src/analytics/private/sqls/redshift/sp-scan-metadata.sql

----
limit value long for customer data

fix: limit value long for customer data

---

src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/realtime.test.ts

fix: stream name to lower case

---

frontend/src/pages/projects/detail/ProjectDetail.tsx

fix: error loading in project details page

---

frontend/src/pages/pipelines/detail/PipelineDetail.tsx

fix: pipeline pending status

---

frontend/src/pages/pipelines/create/CreatePipeline.tsx
frontend/src/pages/pipelines/create/steps/Reporting.tsx
frontend/src/ts/init.ts
frontend/src/ts/utils.ts
frontend/src/types/pipeline.d.ts
frontend/test/msk-redshift.test.tsx
frontend/test/service-available.test.tsx
frontend/test/update-pipeline.test.tsx
src/control-plane/backend/lambda/api/service/environment.ts

fix: reporting check when click next button

---

docs/en/identity-mgmt.md
docs/en/pipeline-mgmt/basic.md
docs/en/troubleshooting.md
docs/en/upgrade.md
docs/zh/identity-mgmt.md
docs/zh/pipeline-mgmt/basic.md
docs/zh/troubleshooting.md
docs/zh/upgrade.md

----
- add 'real dashboard' and 'segments' in role matrix
- add troubleshooting for the server error of web console
- update the template links for China regions

docs: polish doc update to date

---

frontend/src/pages/common/Tags.tsx
frontend/src/pages/pipelines/create/CreatePipeline.tsx
src/base-lib/src/constant/constant.ts
src/control-plane/backend/lambda/api/common/utils.ts
src/control-plane/backend/lambda/api/model/pipeline.ts
src/control-plane/backend/lambda/api/service/stack.ts
src/control-plane/backend/lambda/api/test/api/pipeline.test.ts

fix: revert delete built-in tags and error message when deleting built-in tags

---

frontend/src/pages/analytics/realtime/AnalyticsRealtime.tsx
src/control-plane/backend/lambda/api/service/reporting.ts
src/control-plane/backend/lambda/api/test/api/realtime.test.ts

chore: realtime dashboard embedding type

---

docs/en/pipeline-mgmt/vpc-prerequisites.md
docs/zh/pipeline-mgmt/vpc-prerequisites.md

----
update document for vpc description

docs: update prerequisites of isolated network

---

.projen/deps.json
.projenrc.js
CHANGELOG.md
package.json
pnpm-lock.yaml
solution-manifest.yaml
src/control-plane/backend/lambda/api/.projen/deps.json
src/control-plane/backend/lambda/api/config/dictionary.json
src/control-plane/backend/lambda/api/package.json

Changes for v1.1.11
